### ISSUE TITLE
Text deletion occurs NUL character

### ISSUE THREAD

**Issue by So-chiru** [Riey/kime#112]
Tested on `telegram-desktop` 2.5.1-1 (Qt5)

![1](https://user-images.githubusercontent.com/32066651/105579742-bae13e00-5dcb-11eb-9bf7-b843e7b209ad.png)

Deleting character when only one grapheme remained, creates NUL unicode character (U+0000).

![2](https://user-images.githubusercontent.com/32066651/105579747-bd439800-5dcb-11eb-8c25-d30f32815b1e.png)

![3](https://user-images.githubusercontent.com/32066651/105579794-098ed800-5dcc-11eb-94e7-644aa05c18a9.png)

![4](https://user-images.githubusercontent.com/32066651/105579797-0bf13200-5dcc-11eb-81ea-57c38cb1a2e7.png)

**Comment by Riey** [comment]
Oh I didn't check empty case thank you for report!
