### ISSUE TITLE
마인크래프트에서 한글채팅이 안써집니다.

### ISSUE THREAD

**Issue by GG-O-BP** [Riey/kime#134]
ibus를 사용하다가 최근 kime로 입력기를 변경했습니다.
마인트래프트 자바에디션을 실행하고 멀티서버에서 한글채팅을 입력하려고 했는데, 한영전환이 안됩니다.

ibus로 다시 바꾼 뒤 입력해보니 정상입력 됩니다.
os는 "ubuntu budge 20.10" 입니다.

하드웨어나 시스템관련 추가정보가 필요하면 내일(28일) 중으로 덧글달겠습니다.

**Comment by Riey** [comment]
0.9.0에 좀 오류가 있는것 같은데 좀 있다 0.9.1 릴리즈되면 시험해보실래요?

**Comment by Riey** [comment]
그리고 `/usr/lib/gtk-3.0/3.0.0/immodule.cache`에 kime이 들어있는지도 확인해주세요

**Comment by GG-O-BP** [comment]
![스크린샷, 2021-01-28 20-12-45](https://user-images.githubusercontent.com/36529903/106131233-c8207300-61a5-11eb-804e-542cceccf149.png)
![스크린샷, 2021-01-28 20-16-22](https://user-images.githubusercontent.com/36529903/106131250-ce165400-61a5-11eb-9bf5-5d203662c079.png)

0.9.1로 업데이트 한 후에도 마인크래프트에서 한글텍스트입력이 활성화되지 않습니다.

**Comment by Riey** [comment]
흠 일단 XDG_SESSTION_TYPE 보셔서 X11인지 Wayland인지 확인 부탁합니다

**Comment by GG-O-BP** [comment]
> 흠 일단 XDG_SESSTION_TYPE 보셔서 X11인지 Wayland인지 확인 부탁합니다

늦게 답변드려서 죄송합니다.
"X11"입니다.

**Comment by Riey** [comment]
그러면 kime-xim은 실행된 상태인가요? 또 XMODIFIERS 설정 하셨나요?

**Comment by GG-O-BP** [comment]
> 그러면 kime-xim은 실행된 상태인가요? 또 XMODIFIERS 설정 하셨나요?

실행된 상태고 모두 설정했습니다.
이번에 아치리눅스에도 kime를 셋팅하여 마인크래프트를 실행했으나, 마인크래프트에서 한글채팅사용이 불가했습니다.

제가 보기에 테스트 하실 때는 마인크래프트의 한글채팅에 별 이상이 없으신 것 같은데..
테스트환경을 공유해주시면 저도 동일한 셋팅에서 진행해보겠습니다.

**Comment by Riey** [comment]
아뇨 제가 마인크래프트를 구매하지 않았기 때문에 테스트를 할 수 있는 상황은 아닌거 같습니다 다만 x11에서 다른 swing같은 gui 라이브러리는 테스트를 해봐서 그거랑 비슷하지 않을까 해서 질문을 드려봤습니다.

**Comment by GG-O-BP** [comment]
> 아뇨 제가 마인크래프트를 구매하지 않았기 때문에 테스트를 할 수 있는 상황은 아닌거 같습니다 다만 x11에서 다른 swing같은 gui 라이브러리는 테스트를 해봐서 그거랑 비슷하지 않을까 해서 질문을 드려봤습니다.

현재 마인크래프트 자바에디션이 정확히 어떤 입력프로세스를 가지고있는지는 정확히 모르겠습니다..
제가 개인적으로 테스트할 때는 ibus와 fcitx에서 모두 정상입력됐습니다.

일단은 실행스크립트에서 ibus와 kime를 토글하는 방식으로 사용하고있습미다.

괜찮으시면 마인크래프트 구매비용을 지원해드리고 싶습니다.
현재 기부채널로 드리면 될까요?

**Comment by Riey** [comment]
그렇게 해주신다면 한번 테스트 해보겠습니다

**Comment by XiNiHa** [comment]
> 아뇨 제가 마인크래프트를 구매하지 않았기 때문에 테스트를 할 수 있는 상황은 아닌거 같습니다 다만 x11에서 다른 swing같은 gui 라이브러리는 테스트를 해봐서 그거랑 비슷하지 않을까 해서 질문을 드려봤습니다.

마인크래프트는 LWJGL 써서 그쪽이랑은 입력방식이 완전 다를 겁니다. 아마 LWJGL도 오픈소스일 텐데 그쪽을 보셔도

**Comment by Riey** [comment]
https://github.com/LWJGL/lwjgl3/tree/master/modules/lwjgl/glfw

소스 둘러보니 아마 glfw를 쓰지않나 싶네요

**Comment by Riey** [comment]
https://user-images.githubusercontent.com/14910534/106429596-fce64000-64ad-11eb-8fb8-7de98f61907b.mp4

서버 이름에서 한글 입력되는건 확인했습니다 예상대로 xim을 사용하네요

**Comment by Riey** [comment]
![20210201165723](https://user-images.githubusercontent.com/14910534/106430345-02905580-64af-11eb-864b-682c7fe6b6cb.png)

서버내에서 한글 채팅도 확인해봤습니다 아마 xim이 제대로 실행되지 않았을것 같습니다
