### ISSUE TITLE
Project logo

### ISSUE THREAD

**Issue by Riey** [Riey/kime#160]

**Comment by So-chiru** [comment]
Any concepts you'd like?

**Comment by Riey** [comment]
@So-chiru It would be better to present `Korean IME` in logo such as contains Hangul letter or `K` alphabet

**Comment by So-chiru** [comment]
![image](https://user-images.githubusercontent.com/32066651/107871798-2f4d5f80-6ee8-11eb-850b-7c8f57f8f2df.jpeg)

How about this?

Letter `K` could be colored as Red to Blue if you want to emphasize that IME is Korean IME.

**Comment by Riey** [comment]
Look nice! but Korean letter is not same as real keyboard printing is this intended?

**Comment by So-chiru** [comment]
Letter location can be vary for keyboard manufacturer. letter placing in the example is Apple keyboard.

![image](https://user-images.githubusercontent.com/32066651/107872521-2790b980-6eee-11eb-8eb4-0c1d95cd8620.png)
Standard Keyboard

![image](https://user-images.githubusercontent.com/32066651/107872524-30818b00-6eee-11eb-97c4-fba600fa8eeb.png)
Apple Flavored Keyboard

![image](https://user-images.githubusercontent.com/32066651/107872723-886cc180-6eef-11eb-99ae-02d21d6d01c1.png)
Hexgear Flavored Keyboard

I prefer Hexgear's, how about you?

**Comment by Riey** [comment]
Well, It's just curious I don't care about letter position
