### ISSUE TITLE
neovide에서 중복입력 이슈

### ISSUE THREAD

**Issue by GG-O-BP** [Riey/kime#179]
![1612336135](https://user-images.githubusercontent.com/36529903/106711530-00f39880-663b-11eb-820e-a37d7196b2a7.png)
(kime-xim)

![1612336374](https://user-images.githubusercontent.com/36529903/106711544-0355f280-663b-11eb-9f97-2f67d10536f0.png)
(fcitx5-hangul)

금일 업데이트 받은 후 테스트 중 발견된 버그입니다.

![1612337282](https://user-images.githubusercontent.com/36529903/106712849-e4586000-663c-11eb-9d82-13f840af2cfe.png)

**Comment by GG-O-BP** [comment]
".xprofie"에서 "kime-xim &"를 셋팅했을 때 발생하는 이슈입니다.
해당 셋팅을 하지 않고 kime-xim을 터미널에서 실행 한 뒤 사용할 때는 발생하지 않습니다.

라고 처음에 올렸었는데 재차 테스트해본 결과 양쪽 모두 발생하고 있었습니다.

**Comment by Riey** [comment]
## Good (ibus)

![Screenshot_20210203_163102](https://user-images.githubusercontent.com/14910534/106713366-b293c900-663d-11eb-9967-9c748624c328.png)

## Bad (kime)

![Screenshot_20210203_163115](https://user-images.githubusercontent.com/14910534/106713361-b0ca0580-663d-11eb-8e79-db784bd9a818.png)

**Comment by Riey** [comment]
한글과 동시에 입력되는 문제는 neovide의 버그인것으로 보입니다

![Screenshot_20210203_181736](https://user-images.githubusercontent.com/14910534/106725943-3acd9a80-664d-11eb-9620-c5bfe58c0be8.png)

**Comment by Riey** [comment]
> ## Good (ibus)
> 
> ![Screenshot_20210203_163102](https://user-images.githubusercontent.com/14910534/106713366-b293c900-663d-11eb-9967-9c748624c328.png)
> ## Bad (kime)
> 
> ![Screenshot_20210203_163115](https://user-images.githubusercontent.com/14910534/106713361-b0ca0580-663d-11eb-8e79-db784bd9a818.png)


이 차이는 XIM 구현이 async냐 sync냐의 차이인데 이것도 neovide가 감안해서 패치해줘야 할 것 같습니다 당장은 xim-rs를 sync로 짤 생각은 없습니다.
