### ISSUE TITLE
wayland: Yet another key repeat issue

### ISSUE THREAD

**Issue by simnalamburt** [Riey/kime#207]
![image](https://user-images.githubusercontent.com/4435445/107091115-8f873600-6844-11eb-90ba-b174a7b96884.png)

(56 is <kbd>Alt</kbd>, 2 is <kbd>1</kbd>. There's no release event)

In some cases, virtual-keyboard sends only Press event without Release event. Then, user may experience yet another unwanted key repeat issue.

### How to reproduce
1. Turn on firefox
2. Create two tab
3. On first tab, turn on the Discord app and focus the message input DOM.
4. On second tab, focus the URL bar.
5. Type <kbd>Alt</kbd>+<kbd>1</kbd>

Expected behavior: Firefox switch to the first tab, and nothing happen
Actual behavior: Firefox switch to the first tab, and types <kbd>1</kbd> infinitely

This is because firefox never received release event of <kbd>Alt</kbd> and <kbd>1</kbd>.

NOTE: This issue is **NOT** fixed by https://github.com/Riey/kime/pull/206.

**Comment by Riey** [comment]
> virtual-keyboard sends only Press event without Release event.

Is this screenshot is client side log?

**Comment by simnalamburt** [comment]
> > virtual-keyboard sends only Press event without Release event.
> 
> Is this screenshot is client side log?

That is the trace of kime-wayland sending events to the virtual keyboard.

**Comment by Riey** [comment]
Then it seems compositor doesn't send release event...

**Comment by Riey** [comment]
I can't test reproduce this can you try this patch? https://github.com/Riey/kime/tree/always-grab
