### ISSUE TITLE
Is there any arm build?

### ISSUE THREAD

**Issue by Coder-Iro** [Riey/kime#226]
I'm using Raspberry Pi 4 with Twister OS. I found that there is no release build which target is either armhf or arm64. I think arm build will be really good!

**Comment by Riey** [comment]
It can be build for arm target but I think hard thing is cross compile cause I need `gtk` and `qt` which are giant deps

**Comment by Coder-Iro** [comment]
https://github.blog/changelog/2019-12-03-github-actions-self-hosted-runners-on-arm-architectures/

**Comment by Riey** [comment]
Wow.. I didn't know that I'll try setup actions

**Comment by Riey** [comment]
Thank you @simnalamburt  then it can't be apply kime :(

**Comment by Riey** [comment]
Merged into #148
