### ISSUE TITLE
GTK 프로그램에서 한글 입력 문제 

### ISSUE THREAD

**Issue by lindoli** [Riey/kime#259]
새로운 한글입력기 kime 개발에 축하드리며, 리눅스 모든 배포판에 공통적으로 사용될 수 있는 입력기로 발전하길 기원합니다.

우연히 kime을 알게 되어, rpm 패키지로 컴파일하여 사용해 보았는데, QT5 환경에서는 잘 작동합니다만, GTK 환경에서는 전혀 한글 입력이 안되는군요. 패키징 문제인지, 아니면 GTK 라이브러리 문제인지 모르겠습니다만, GTK에서만 안됩니다. 

.i18n 파일 
CONSOLE_NOT_LOCALIZED=yes
ENC=utf8
LANG=ko_KR.UTF-8
LANGUAGE=ko_KR.UTF-8:ko
LC_ADDRESS=ko_KR.UTF-8
LC_COLLATE=ko_KR.UTF-8
LC_CTYPE=ko_KR.UTF-8
LC_IDENTIFICATION=ko_KR.UTF-8
LC_MEASUREMENT=ko_KR.UTF-8
LC_MESSAGES=ko_KR.UTF-8
LC_MONETARY=ko_KR.UTF-8
LC_NAME=ko_KR.UTF-8
LC_NUMERIC=ko_KR.UTF-8
LC_PAPER=ko_KR.UTF-8
LC_TELEPHONE=ko_KR.UTF-8
LC_TIME=ko_KR.UTF-8
GTK_IM_MODULE=kime
QT_IM_MODULE=kime
XMODIFIERS=@im=kime
XIM_PROGRAM=kime-xim

# rpm packaging lists
/etc/xdg/kime/config.yaml
/usr/bin
/usr/bin/kime-indicator
/usr/bin/kime-wayland
/usr/bin/kime-xim
/usr/include/kime_engine.h
/usr/include/kime_engine.hpp
/usr/lib64/gtk-2.0/2.10.0/immodules/im-kime.so
/usr/lib64/gtk-3.0/3.0.0/immodules/im-kime.so
/usr/lib64/libkime_engine.so
/usr/lib64/qt5/plugins/platforminputcontexts/libkimeplatforminputcontextplugin.so
/usr/share/applications/kime.desktop
/usr/share/icons/kime-eng-64x64.png
/usr/share/icons/kime-han-64x64.png

GTK 환경에서 kime 라이브러리가 im-kime.so 인지 아니면 libkime-gtk2.so, libkime-gtk3.so 인지 정확하게 알려 주시면 감사하겠습니다.

**Comment by Riey** [comment]
안녕하세요 kime에 관심을 가져주셔서 감사합니다
qt는 특정경로안에 있는 immodule을 자동으로 불러오지만 gtk는 사용전에 immodule을 캐싱해야 합니다 그리고 그 방법은 배포판별로 조금씩 다릅니다.

우선 이 [링크](https://developer.gnome.org/gtk3/stable/gtk-query-immodules-3.0.html)랑 리드미의 gtk [챕터](https://github.com/Riey/kime/blob/develop/README.ko.md#gtk)를 보시고 캐시를 업데이트 해보시길 바랍니다.

**Comment by Riey** [comment]
그리고 immodule들의 이름은 그냥 컨벤션이고 시도는 안해봤지만 다른 이름이라도 작동에 문제는 없을것으로 예상합니다 일단 `im-kime.so`를 사용하며 다른 IME들도 비슷한 형식을 취하고 있습니다.

**Comment by lindoli** [comment]
immodule 캐싱을 한 후 정상적으로 동작되어 있습니다. rpm spec에 rpm 패키지 설치시에 기본적으로 immodule 캐시가 업데이트되도록 했습니다.

감사합니다.

**Comment by Riey** [comment]
혹시 괜찮으시면 패키지 파일을 올려주실수 있으신가요? 나중에 rpm 패키징을 할때 참고할수 있다면 도움이 많이 될것 같습니다.

**Comment by lindoli** [comment]
RPM spec 파일을 첨부합니다. 

제가 프로그래머가 아니라서 좀 허접할 수 있겠지만, RPM 기반 배포판에서는 매크로 정의대로 수정해서 리빌드하면 될 것입니다.

[kime.spec.zip](https://github.com/Riey/kime/files/5986505/kime.spec.zip)

**Comment by Riey** [comment]
이 이슈를 다시 여신 이유가 있나요?

**Comment by lindoli** [comment]
> 이 이슈를 다시 여신 이유가 있나요?

죄송합니다. 마지막 댓글을 올리려다보니 재오픈했는데, 클로징하겠습니다.
