### ISSUE TITLE
ComposeChoseongSsang 활성화 시 초성 합성 문제

### ISSUE THREAD

**Issue by 80ROkWOC4j** [Riey/kime#263]
세벌식 390으로 사용중인데 ComposeChoseongSsang 애드온을 활성화 할 경우 중성이나 종성이 입력된 상태여도 초성이 입력될 경우 기존 초성에 조합됩니다.
예를 들어 "각기"를 입력하면 "각" 입력후 다음 초성 "ㄱ", "ㅣ" 입력시
"각ㄱ" -> "각기" 가 되지 않고
"깍" -> "까기" 로 조합됩니다.
그리고 ~/.config/kime/config.yaml에서 애드온을 모두 지우면 전역 설정이 로드 되는데 의도된 사항인가요?

**Comment by Riey** [comment]
전역이 로드되는건 전혀 예상치 못한 버그네요 자고 일어나서 낮에 한번 보겠습니다.

**Comment by Riey** [comment]
확인결과 애드온을 지운다고 전역설정이 로드되지는 않습니다
지금 구현에선 설정 로드에 실패할 경우 디폴트 설정을 로드하며 이 디폴트 설정은 따로 파일에서 읽는건 아니고 프로그램에 내장되어 있습니다
