### ISSUE TITLE
일부 Qt 프로그램에서 한글 입력 문제 

### ISSUE THREAD

**Issue by lindoli** [Riey/kime#277]
일부 Qt 프로그램에서 한글 입력 문제가 있습니다. 이것은 kime 자체의 문제가 아니라, 해당 프로그램에서 ime 지원상의 문제라 판단하고 있지만, 그래도 개발자님은 해결책이 있을까 싶어서 문의드립니다.

문제시 되는 Qt 프로그램은 화면 캡쳐 프로그램인 ksnap과 Spectacle입니다. 이들 프로그램에서 공통된 입력 문제를 야기하고 있는데, 한글을 입력하게 되면 제대로 입력되지 않고 서로 앞뒤로 밀리면서 엉뚱하게 입력된다는 점입니다. 

예를 들어 '한글 스펙터클'을 입력하게 되면 첨부한 이미지처럼 '글스터 한클펙'으로 입력되는 문제가 있습니다. 이것은 비단 kime 뿐만 아니라 uim, fcitx등 다른 입력기에서도 문제가 발생합니다.  이러한 문제는 다음 링크에 있는 게시물에서 발생하는 증상과 같거나 유사하지 않을까 생각합니다. 

https://github.com/korean-input/issues/issues/9
![kime-spec](https://user-images.githubusercontent.com/79091785/108456427-a3ef1800-72b3-11eb-8217-94f23b53aa4e.jpg)

**Comment by Riey** [comment]
캡쳐후에 편집기능을 쓰는건가요?

**Comment by lindoli** [comment]
네 그렇습니다. ksnip는 편집 기능이 원래부터 있었지만, 한글 입력 지원이 안됐었고요, KDE 환경의 대표적인 캡쳐 프로그램인 spectacle은 편집 기능이 없다가 언제부턴지 모르겠지만, 추가되었는데, ksnip과 동일한 한글입력 문제가 있습니다.

**Comment by Riey** [comment]
음 모든 입력기에서 발생한다면 여기가 아니라 https://github.com/korean-input/issues 여기에 올릴 이슈같군요

**Comment by Riey** [comment]
원래는 이슈를 transfer 시키는게 맞지만 애석하게도 다른 organization에 보내는것은 안되므로 닫겠습니다 저기에 열어주시길 바랍니다
