### ISSUE TITLE
PhpStorm 에서 한글 띄어쓰기에 문제가 있습니다.

### ISSUE THREAD

**Issue by chwnam** [Riey/kime#283]
우선 이런 한글 입력기 프로젝트가 있어 너무 감사합니다.
저는 리눅스 민트 시나몬 데스크탑을 이용하는 유저이고, 주로 nimf를 이용해 한글 입력을 하고 있습니다.
가끔 kime으로 입력을 전환해 테스트도 해 보고 있습니다.

kime에서 발견한 문제가 있어 이슈로 남기고자 합니다.
PhpStorm에서 한글 입력시 한글 입력은 되지만 띄어쓰기에 문제가 발생합니다.
예를 들면 "한글 입력은 되지만 띄어쓰기가 올바르지 않게 됩니다."라는 문장을 입력하면 "한 글입력 은되지 만띄어쓰기 가올바르 지않 게됩니다."처럼 스페이스바가 위치해야 할 곳 하나 앞서 들어가게 되는 문제가 있습니다.

![image](https://user-images.githubusercontent.com/6630320/108601873-4b6a6880-73e2-11eb-958f-907c4aa8c2bd.png)

**Comment by Riey** [comment]
1.1.0에서도 동일한 증상이 발생하나요?
