### ISSUE TITLE
한영키 키보드 맵핑 

### ISSUE THREAD

**Issue by lindoli** [Riey/kime#291]
그동안 랩톱에서만 kime를 사용해서 불편한 점을 모르고 있었는데, 데스크탑의 키보드로 사용할 때 한영키 맵핑 문제로 불편을 느끼고 있습니다. 현재 한영키가 오른쪽 ALT로 되어 있는데, 랩톱에선 한영키와 같이 사용되어서 문제시 되지 않지만, 데스크탑 키보드에서는 이게 분리되어 있다보니 104키의 한영키와 맵핑되질 않네요.

xmodmap를 통해서 한영키를 130 키코드로 맵핑해도 kime에서는 AltR(keycode 108)로만 적용되는데, 104/105키에서 AltR 대신에 한영키로 적용되게 끔 하는 방법을 알고 싶습니다.

**Comment by Riey** [comment]
`xev -event keyboard`로 해당 한영키의 키코드가 얼마로 나오는지 확인해주세요 130으로 나오나요?

**Comment by Riey** [comment]
kime은 keysym을 읽지 않으므로 xmodmap으로 설정하시는건 kime의 동작에는 영향이 없고 현재 Hangul은 122번 keycode에 대응되는데 혹시 지금 쓰시는 키보드가 어떻게 생겼나요? 130도 쓰인다면 매핑을 좀 바꾸겠습니다.

**Comment by lindoli** [comment]
104/105키에서는 keycode가 130입니다. 
![han-keycode](https://user-images.githubusercontent.com/79091785/108679695-474c6100-7530-11eb-8606-b000f5b41301.png)

**Comment by Riey** [comment]
@lindoli 혹시 `q` 누르면 키 코드가 얼마로 나오나요?

**Comment by lindoli** [comment]
q키는 24입니다.

**Comment by Riey** [comment]
지금 develop 브랜치 빌드해보시면 아마 될겁니다 다음 릴리즈까지 기다려 주세요

**Comment by lindoli** [comment]
keycode 130 적용이 잘 됩니다. 그런데, altr를 한영 맵핑에서 제외하였으면 하는데, 이것은 어떻게 하면 될까요?

한영키(keycode 130)를 적용한 상태에서 옆키인 altr도 한영이 중복되다보니 다른 용도로 AltR를 다른 용도로 사용하고자 할 때도 불편함이 있을 듯 싶습니다. config.yaml에서 AltR 맵핑 설정을 제거해도 AltR은 기본값으로 설정되어 있는 듯 합니다.

**Comment by Riey** [comment]
그건 좀 이상하네요 설정파일을 올려보실래요?

**Comment by lindoli** [comment]
죄송합니다. /etc/xdg/kime와 ~/.config/kime 두 경로에 중복 설정을 두다 보니 이런 혼동을 야기한 것 같습니다. 사용자 경로의 설정 파일을 삭제한 후에는 정상적으로 동작함을 확인하였습니다. 

감사합니다.
