### ISSUE TITLE
한자나 특수문자 입력은 어떻게 하나요?

### ISSUE THREAD

**Issue by chwnam** [Riey/kime#293]
보통 한자는 한글을 입력한 후에, 특수문자는 자음 하나를 입력한 후 각가 한자 키를 누르면 변환할 수 있는 문자 목록이 나오잖아요?
KIME에서는 어떻게 한자, 특수문자 변환을 하는지요?

**Comment by Riey** [comment]
아쉽게도 아직 미구현 상태입니다

**Comment by chwnam** [comment]
감사합니다. 구현이 될 수 있으면 좋겠네요.
