### ISSUE TITLE
kdenlive 렌더링 충돌 이슈 

### ISSUE THREAD

**Issue by lindoli** [Riey/kime#294]
kdenlive에서 렌더링할 때 kime 모듈과 호환 문제로 인해서 렌더링이 안되는 문제가 발생하는데, 이 부분을 확인 좀 해 주셨으면 합니다. 

참고로, 이미지에 있는 kime immodule 버전만 그런게 아니라 모든 버전에서 발생하며, kime 모듈을 삭제해야만 정상적인 렌더링이 가능해집니다. kime 1.1.0 버전으로도 시도해 보았으나, 결과는 같습니다.

![kdkenlive-kime](https://user-images.githubusercontent.com/79091785/108792113-e0788780-75c3-11eb-82f6-d86e9757a80d.png)

**Comment by Riey** [comment]
버전문제 같은데 직접 빌드해서 시스템 버전이랑 맞춰도 발생하나요?

**Comment by lindoli** [comment]
libkime-qt5.so를 개발자님이 빌드하신 걸로 대체하다보니 일반적으로 사용할 때는 문제가 없다가 kdenlive와 같은 일부 프로그램에서 문제가 발생되는 듯 싶은데, 아직 melt과 호환 여부를 파악하지 않아 정확한 것은 아직 모르겠군요.  가능하다면 libkime-qt5.so를 kime 빌드할 때 같이 빌드될 수 있도록 하였으면 합니다.

**Comment by Riey** [comment]
직접 빌드하시면 같이 빌드될텐데요 일단 시스템 qt 버전은 어떻게 되나요

**Comment by lindoli** [comment]
zoom 때문에 헷갈린 부분이 생긴 것 같습니다. zoom 지원하기 위해서 kime rpm build할 때 libkime-qt5.so를 개발자님이 제공하신 파일들을 포함하여 빌드해서 qt5 경로에 집어 넣었던 건데, kdenlive에서 예기치 않은 렌더링 오류가 발생되었던 겁니다. 그래서 다운로드한 qt용 모듈 파일을 삭제한 후에는 kdenlive에서 렌더링 이슈가 발생되지 않았는데, 오히려 zoom에서 예전 초기 이슈가 재발생했습니다. 

1.1.0 버전을 가지고 재테스트해 보았으나, zoom 한글 입력이 안되어, 개발자님이 제공한 qt 5.9.5 버전으로 대체하니 zoom에서도 정상적으로 동작했는데, 여기서 또 혼동이 발생된 것은 왜 내가 리빌드한 패키지의 qt 모듈로는 zoom에서 동작하지 않을까 고민했습니다. 

그런데 제가 간과했던 것이 zoom을 직접 빌드한 것이 아니라, 데비안 패키지를 rpm 패키지로 리패키징해서 사용했던 거라, 데비안 패키지 버전에 맞는 kime qt 모듈을 사용해야 했던 것이지요(이걸 까먹고 있었는데, 나이 들어서 건망증이 심해서 더 그런 듯) 그래서 제가 빌드한 패키지로는 적용이 안되었던 거고, zoom에서는 개발자님이 제공하신 모듈을 그대로 사용해야 했던 것이지요. 

제 혼동으로 이슈같지 않은 이슈를 만들어 불편을 드려 죄송하군요.

이 이슈는 종료하겠습니다.

**Comment by Riey** [comment]
먼저 알아야 하실건 zoom같은 특정 어플만 대상 Qt 버전이 다르다는것입니다(이 경우 5.9) 대다수의 어플은 시스템 Qt에 맞춰서 빌드됐으니 그에 맞는 버전을 받으시면 됩니다 

굳이 deb를 받으실것도 없고 그냥 kime-v1.1.1.tar.zst랑 원하시는 qt so 파일만 받아서 합치시면 됩니다 releases에 있는 아카이브들 내용물은 전부 이 qt의 버전차이가 있을 뿐 입니다 :)

**Comment by lindoli** [comment]
제가 잘못 이해한 건지 아니면 잘못 전달해 드린 건지 모르겠습니다만, kime deb 패키지를 받아 리빌드했다는 것이 아니고요, zoom 패키지가 제 배포판에 맞게 빌드된 것이 없어서 zoom deb 패키지를 다시 rpm 패키지로 빌드해서 사용하고 있다는 얘기입니다. 그래서 줌을 사용할 때는 개발자님이 제공해 주신 libkime-qt5.so 파일을 사용해야 한다는 의미였습니다.

**Comment by Riey** [comment]
아 제대로 사용하고 계시는군요 제가 잘못 생각했나봅니다.
