### ISSUE TITLE
kime-check failed

### ISSUE THREAD

**Issue by Riey** [Riey/kime#307]
![20210224183005](https://user-images.githubusercontent.com/14910534/108980226-caa3b900-76ce-11eb-94a9-6e0297c80059.png)

**Comment by lindoli** [comment]
1.1.0에서 engine  동작 체크엔 문제가 없었는데, 패치되었다던 1.1.3에선 상기 오류가 발생되는군요.

다른 버전을 확인해 보니깐 상기 오류는 1.1.2 버전부터 발생한 것으로 보이며, 1.1.3에서도 여전히 발생되는 것으로 확인됩니다.
