### ISSUE TITLE
kime-indicator 컴파일 

### ISSUE THREAD

**Issue by lindoli** [Riey/kime#350]
1.2.x 버전까지는 kime-indicator 바이너리 생성을 체크하였습니다만, 그 이후에는 kime 자체가 잘 동작하다보니 1.3.x 버전대에서는 컴파일시 kime-indicator를 확인하지 못했는데, 다른 시스템에서 1.3.x 버전을 설치하다보니 kime-indicator가 없는 걸 알았습니다.
그래서 scripts/build.sh 파일을 열어 보았는데, kime-indicator 생성에 관한 것이 없더군요. 1.3 버전대에서는 이 바이너리 생성 방법이 달라졌는지요?

--- build.sh    2021-02-26 01:56:53.000000000 +0900                      <--- 1.2.x ver
+++ build-new.sh        2021-03-02 16:10:06.000000000 +0900        <--- 1.3.x ver
@@ -67,18 +67,16 @@
     cp $TARGET_DIR/kime-check $KIME_OUT
 fi
 
-echo Build xim wayland indicator...
+echo Build xim wayland...
 
-cargo_build -p kime-xim -p kime-wayland -p kime-indicator
+cargo_build -p kime-xim -p kime-wayland
 
 cp $TARGET_DIR/kime-xim $KIME_OUT
 cp $TARGET_DIR/kime-wayland $KIME_OUT
-cp $TARGET_DIR/kime-indicator $KIME_OUT
 cp src/engine/cffi/kime_engine.h $KIME_OUT
 cp src/engine/cffi/kime_engine.hpp $KIME_OUT
 cp LICENSE $KIME_OUT
-cp res/default_config.yaml $KIME_OUT
-cp -R res/icons $KIME_OUT
+cp -R res/* $KIME_OUT

**Comment by Riey** [comment]
한자나 이모지 입력을 넣으면서 규모나 빌드시간이 많이 커진 관계로 별도 저장소에 분리하였습니다



https://github.com/Riey/kime-window
