### ISSUE TITLE
약간의 기부를 드리고 싶습니다.

### ISSUE THREAD

**Issue by chwnam** [Riey/kime#358]
좋은 프로젝트를 진행해 주셔서 너무 감사합니다. 저도 프로젝트에 도움이 되고 싶지만,
이 쪽으로는 전혀 지식이 없어 실질적인(개술, 개발적인) 도움은 어렵습니다. 

하지만 저는 매일매일 리눅스 민트로 작업을 하는 사람입니다. 맥, 윈도우에 비해 뭔가 부족한 한글 입력은 늘 아쉬웠습니다. 리눅스 한글 입력기는 요즘 나름 많이 괜찮아졌디만, 그래도 어디선가 하나씩 나사가 빠져 있어 불편합니다. 제 생각인데, 한국어 사용자에게 있어 가장 큰 장벽 중 하나는 한글 입력임은 예전이나 지금이나 크게 다르지 않은 것 같습니다.

좋은 한글 입력기를 원하는 마음은 너무 간절합니다. 기존에 nimf라는 프로젝트가 있었지만, 뭔가 잘 안되어 안타깝던 마당에 kime은 가뭄에 단비와 같습니다. 이 프로젝트가 정말로 오랫동안 잘 유지되었으면 하는 마음입니다.

이런 프로젝트가 조금이라도 더 활성화되면 좋겠다는 마음에 기부를 하고 싶습니다. 비록 저 개인이 큰 액수를 기부하는 것은 무리지만...
아마 저 말고도 다른 분들도 기부를 하실 수 있으리라 생각합니다. 그러면 좀 더 좋은 한글 입력기가 될 수 있을까요?
프로젝트 진행이 좀 더 원활해 질 수 있을까요?

만약 기부가 프로젝트 진행해 좋은 영향을 미칠 수 있다면 기부하고 싶습니다.
그런데 어떻게 해 드려야할지 모르겠어요. 의향이 있으시다면 기부 방법에 대해서도 알려주셨으면 좋겠습니다.

**Comment by Riey** [comment]
관심을 가져주셔서 감사합니다 기부 링크는 리드미에 달아는 두고 있습니다

kime은 타 입력기에 비교하여 기능이 많이 부족하지만 대신 한글입력만큼은 최대한 버그없이 구현하기 위해 노력하고 있습니다 타 입력기가 다국어 지원등으로 해결이 어려운 문제의 해결에는 kime이 빈자리를 채울 수 있다고 생각합니다.

[<img src="https://d1u4yishnma8v5.cloudfront.net/mobile-gift.png" alt="donaricano-btn" height="50">](https://donaricano.com/mypage/1610220543_mjZDXO)

**Comment by lindoli** [comment]
우리나라에선 기부 문화가 활성화되어 있지 않아 안타까운 면도 없지 않습니다. 저 역시 chwnam님과 같은 생각을 가져오고 있었는데, 때마침 chwnam님이 제안하셔서 비록 큰 액수는 아닐지언정 kime이 지속적으로 개발되길 염원하는 차원에서 도네이션에 저도 동참하기로 하였습니다. 

보다 안정적인 한글입력기 개발을 바라는 사용자가 있다면 이러한 좋은 취지의 기부 문화에 동참하여 확산되었으면 하는 바람입니다. 

저는 나비 이후에 국내에서 개발된 한글입력기로 kime를 만족스럽게 사용하고 있어서 Riey님께 늘 고마움을 느끼고 있습니다.

**Comment by GG-O-BP** [comment]
저도 저번달부터 소액 도네이션을 하고있습니다.
Riey님이 달아주신 커피를 들고있는 동그란 아이콘링크인 도네리카노로 하고있습니다.

**Comment by chwnam** [comment]
![image](https://user-images.githubusercontent.com/6630320/111094124-e38ce500-857d-11eb-9edf-6c008174d533.png)

저 아이콘이 도네이션인 줄 몰랐어요!
소정의 기부 드렸습니다. 매일 깃헙 페이지 방문하면서 업데이트를 보고 있습니다.
더욱 좋은 한글 입력기가 되기를 진심으로 응원합니다.
