### ISSUE TITLE
v2.0.0 indicator

### ISSUE THREAD

**Issue by lindoli** [Riey/kime#375]
v2.0.0 릴리즈에 감사합니다. 

v2.0.0에서 kime-windows가 원래대로 kime-indicator로 바뀌었는데, 앞으로도 kime-indicator로 통합해서 지원하실 예정인지요?

**Comment by Riey** [comment]
네 appindicator 의존성이 없어지기도 하고 입력방식이 많이 바뀌어서 분리할 필요가 없어졌네요 그런데 지금 한글입력에 문제가 좀 있으니 바로 업그레이드는 하지 말아주세요
