### ISSUE TITLE
한자 입력할 때 이상한 현상이 있습니다.

### ISSUE THREAD

**Issue by chwnam** [Riey/kime#381]
KIME 2.0.1 버전을 리눅스 민트 20.1 시나몬 버전 (우분투 20.04)에 설치해서 사용 중입니다.
이번에 업데이트된 KIME에서 한자 입력시 이상한 현상이 있어 제보드립니다.

https://user-images.githubusercontent.com/6630320/111715082-6ec7ec80-8896-11eb-8743-d2d1d380abea.mp4

단어 입력 후 한자 키를 입력하면 한자 목록을 선택하는 것이 아닌, 본문에 한자가 주르륵 나열되는 일이 일어납니다. 그 나열된 문자열을 클릭하면 가장 첫번째 한자가 나오는 것 같네요. 아무튼 한자를 정확히 입력하기 어려운 것 같습니다.

**Comment by Riey** [comment]
2.0으로 오면서 한자 입력 방식이 바뀌었습니다 방향키 왼쪽 오른쪽으로 움직여서 고르시고 엔터나 스페이스를 입력하시면 됩니다

**Comment by chwnam** [comment]
@Riey 
방향키를 왼쪽 오른쪽으로 움직여도 한자 선택이 되지 않습니다.
예를 들어 '가'를 입력 후 한자 키를 누르면 먼저 집 가(家)자가 나오는데, 다른 한자를 선택하려고 왼쪽, 오른쪽 키, 심지어 마우스 커서까지 동원해도 집 가자 이외에는 선택을 할 수가 없습니다.

**Comment by Riey** [comment]
그건 확실히 버그군요 확인해 보겠습니다

**Comment by Riey** [comment]
아 문제를 찾았네요 다음 릴리즈에 반영하겠습니다 제보 감사합니다
