### ISSUE TITLE
Indicator icon is empty in first start

### ISSUE THREAD

**Issue by Riey** [Riey/kime#386]

**Comment by lindoli** [comment]
v2.0.0에서 아이콘 경로와 파일명이 기존과 좀 다르더군요.

v2.0.0 : /usr/share/kime/icons/64x64/kime-hangul/latin-black/white.png
실제경로:/usr/share/kime/icons/kime-han-black/white-64x64.png

build/out/icons에 있는대로 빌드한 기존 패키지 스펙을 변경했더니, indicator에서 아이콘이 보이질 않더군요.
kime-check 도구로 확인해 보니깐 이 도구와 indicator가 찾는 아이콘은 기존 경로와 파일명을 찾는 듯 싶습니다. 
그래서 실제경로와 파일명을 기존대로 하니 kime-check에서 아이콘을 찾는군요. 하지만, 영문 아이콘은 경로와 파일명이 
다른지 나타나지 않습니다. 그래서 시작시 아이콘이 보이질 않는 것으로 생각합니다.

전체적으로 빌드할 때 생성되는 아이콘 파일명과 경로로 패키징할 때 일치되도록 인식되게 끔 해 주시는 것이 어떨련지요?

**Comment by Riey** [comment]
@lindoli build/out에 있는 경로는 아무 의미가 없습니다 참고하시려면 install.sh를 참고해주세요 그리고 그건 kime-check 버그입니다 현재 통상의 배포판의 아이콘 경로는 `/usr/share/icons/hicolor/64x64/apps/kime-hangul-black.png` 입니다

**Comment by lindoli** [comment]
/usr/share/icons/hicolor/64x64/apps 경로에 아이콘을 넣으니 kime-indicator에서 정상적으로 아이콘화됨을 확인하였습니다. 

이제까지 kime-check에서 체크한 경로대로 패키징했는데, 앞으로는 이 경로를 기본으로 해야겠군요.

v2.1.0 버전에서는 첫 실행시 아이콘이 정상적으로 나옵니다. 

감사합니다.

**Comment by Riey** [comment]
흠 그러면 indicator 구현체에 따라 발생이 달라질수도 있겠네요 일단 waybar에선 바로 나오진 않습니다

**Comment by Riey** [comment]
아무래도 제가 쓰는 waybar의 구현 문제같습니다 kime이 뭔가 할건 없어보이네요.
