### ISSUE TITLE
kime-indicator 가 로그아웃 후에 종료되지 않습니다.

### ISSUE THREAD

**Issue by chwnam** [Riey/kime#387]
kime_ubuntu-20.04_v2.1.0_amd64.deb 패키지로 설치하였고, im-config 로 kime을 사용하도록 설정해 두었습니다.
세션 시작하면서 kime은 실행되지만, kime-indicator는 같이 실행되지 않아 따로 실행하도록 처리하였습니다.

![image](https://user-images.githubusercontent.com/6630320/111750792-03523f00-88d7-11eb-89fa-40212f7e1e9a.png)

그런데 이렇게 실행된 kime-indicator는 사용자 로그아웃 후 종료되지 않는 것 같습니다.
3번정도 로그아웃-로그인을 해서, 

![image](https://user-images.githubusercontent.com/6630320/111751194-870c2b80-88d7-11eb-90dd-d4e676648d10.png)

indicator가 그림처럼 중복되어 보이는 것을 보았습니다.

**Comment by Riey** [comment]
혹시 kime-xim도 여러번 실행되나요?

**Comment by chwnam** [comment]
> 혹시 kime-xim도 여러번 실행되나요?

kime-xim 은 로그아웃 때 정상적으로 종료되는 것으로 보입니다. 한 번 로그아웃 후에 ps ax 한 스크린샷 첨부할께요.

![image](https://user-images.githubusercontent.com/6630320/111857660-4e6f5f00-8976-11eb-9b97-69e6652b0db2.png)

**Comment by Riey** [comment]
kime-xim은 X서버랑 같이 종료되나 보군요 일단 2.1.1에는 고쳐졌습니다
