### ISSUE TITLE
파이어폭스 input, textarea 입력시 home / end / pg up / pg dn 키가 동작하지 않습니다.

### ISSUE THREAD

**Issue by chwnam** [Riey/kime#410]
![image](https://user-images.githubusercontent.com/6630320/112085543-13676880-8bce-11eb-9474-c1c295772274.png)

리눅스 민트 (우분투 20.04), 에 파이어폭스 86 사용 중입니다.
여기 github의 textarea는 물론, 일반적인 input type="text", textarea 위젯에서 한글 입력시 일어나는 현상입니다.

1. 한글 입력 중이고, 입력 중인 바로 그 글자에 밑줄이 쳐져 있을 때,
2. home / end / pg dn / pg up 키가 동작하지 않습니다.
3. 쉬프트 키와 조합할 경우에도 마찬가지로 동작하지 않습니다.

- 다른 입력기에서는 해당 현상이 발생하지 않습니다.
- 제 경우 파이어폭스 브라우저와 카임 조합시에 한정적으로 일어나는 버그로 보입니다.
  (사용중인 웹브라우저가 당장 비발디와 파이어폭스 2가지라 폭넓게 테스트는 하지 못했어요)

이게 파이어폭스 한정의 문제인지, kime의 문제인지는 잘 알 수없지만, 
현상 발견하여 일단 제보는 드립니다.

**Comment by Riey** [comment]
kime 버전이 몇인가요?

**Comment by chwnam** [comment]
> kime 버전이 몇인가요?

v2.2.0입니다.
