### ISSUE TITLE
PhpStorm에서 search everywhere 메뉴가 쉬프트 두번 누르는 것으로 실행되지 않습니다.

### ISSUE THREAD

**Issue by chwnam** [Riey/kime#418]
PhpStorm(아마 JetBrains IDE 다른 제품군에서도) 에서 "Search Everywhere"라는 검색창이 있는데,
이 메뉴를 띄우는 핫 키는 쉬프트를 연속으로 두 번 누르는 것입니다.

kime 사용시에 이 Search Everywhere 검색창이 나타나지 않는 문제가 발견됩니다.

**Comment by Riey** [comment]
이 패키지를 시험해 보실래요?

[kime.tar.gz](https://github.com/Riey/kime/files/6202215/kime.tar.gz)

**Comment by chwnam** [comment]
> 이 패키지를 시험해 보실래요?
> 
> [kime.tar.gz](https://github.com/Riey/kime/files/6202215/kime.tar.gz)

이걸로 해 보니 문제가 해결되는군요!
