### ISSUE TITLE
카카오톡 한글 입력 오류 

### ISSUE THREAD

**Issue by lindoli** [Riey/kime#420]
kime를 잘 사용중입니다. 그런데, 카카오톡에서 한글 입력시 오류가 발생됨이 확인되었습니다. 

이슈버전 : kime 2.2.0 이상 
증상: 한글 입력시 제대로 입력되지 않음 

이슈를 확인하기 위해 2.3.0 버전부터 2.0.0 이전버전까지 모두 테스트해 보았는데, 2.2.0 버전부터 증상이 발생된 것으로 보입니다. 

확인 부탁드립니다.
![ka-kime-err](https://user-images.githubusercontent.com/79091785/112589817-1a4be080-8e45-11eb-983d-784f5c085ec9.png)

**Comment by Riey** [comment]
@lindoli xim 서버를 `kime-xim --verbose`로 실행한뒤 카카오톡에 입력할때 나오는 로그를 올려주실수 있으신가요?

**Comment by lindoli** [comment]
요청하신 로그입니다. 

[DEBUG] (1) xim::server::connection: <-: ForwardEvent
11:04:44 [TRACE] (1) xim::server::connection: [/root/.cargo/registry/src/github.com-1ecc6299db9ec823/xim-0.1.1/src/server/connection.rs:231] <-: ForwardEvent { input_method_id: 1, input_context_id: 6, flag: (empty), serial_number: 0, xev: XEvent { response_type: 2, detail: 27, sequence: 7213, time: 476978, root: 1721, event: 81788965, child: 0, root_x: 403, root_y: 825, event_x: 75, event_y: 521, state: 0, same_screen: true } }
11:04:44 [TRACE] (1) kime_xim::handler: [src/frontends/xim/src/handler.rs:275] KeyPressEvent { response_type: 2, detail: 27, sequence: 7213, time: 476978, root: 1721, event: 81788965, child: 0, root_x: 403, root_y: 825, event_x: 75, event_y: 521, state: 0, same_screen: true }
11:04:44 [TRACE] (1) kime_xim::handler: [src/frontends/xim/src/handler.rs:300] 5
[DEBUG] (1) xim::x11rb: ->: PreeditDraw
11:04:44 [TRACE] (1) xim::x11rb: [/root/.cargo/registry/src/github.com-1ecc6299db9ec823/xim-0.1.1/src/x11rb.rs:677] ->: PreeditDraw { input_method_id: 1, input_context_id: 6, caret: 1, chg_first: 0, chg_length: 1, status: (empty), preedit_string: [27, 37, 71, 235, 160, 165, 27, 37, 64], feedbacks: [Underline] }

**Comment by Riey** [comment]
`IC created style`가 포함된 줄은 어떻게 뜨나요?

**Comment by Riey** [comment]
혹시 로그에 ForwardEvent가 무수히 뜨나요?

**Comment by lindoli** [comment]
한글을 입력할때마다 첨부하였던 로그 메시지들이 계속 나옵니다. 

그리고 IC created style에 관련된 메시지는 다음과 같습니다.

[ INFO] IC created style: PREEDIT_CALLBACKS | STATUS_NOTHING, spot_location: Point { x: 0, y: 0 }

**Comment by Riey** [comment]
키 입력을 안해도 스크롤이 계속 올라가시면 무슨 문제인지는 알것 같네요 재현은 저도 되니 일단 나중에 디버깅 해보겠습니다 그런데 혹시 디스코드 채널에 들어오시지 않으실래요?

버그제보야 이슈에 올리시는게 좋지만 채팅으로 하는게 편한 질문들도 종종 있으니까요 초대링크는 리드미에 있습니다 관심있으시면 들어오세요.

**Comment by lindoli** [comment]
키보드 입력시에만 스크롤이 올라가고요, 키보드 입력이 없을 때는 아무런 변화가 없습니다. 

디스코드 채널은 시간적인 여유가 없다보니 채팅을 하기는 어려움이 있긴 한데, 여유가 되는대로 참여해 보도록 하죠.

감사합니다.

**Comment by Riey** [comment]
음 저는 wine에서 Preedit이 안되네요 wine 버전이 얼마인가요?

**Comment by lindoli** [comment]
제가 사용하고 있는 wine 버전은 다음과 같습니다. 

wine-mono-5.1.1
wine-gecko-2.47.2
wine32-6.0
wine64-6.0ㅡㄹ 구
winetricks-20200412

wine은 가급적 5.0 이상 버전 사용을 추천합니다. wine를 4.x 버전을 사용하는 경우에는 wine-mono 만큼은 5.x 버전대로 사용할 것이 좋습니다. 

그 이유는 카카오톡을 설치할 때 라이브러리를 추가로 설치할 필요가 없기 때문입니다. 

저는 레지스트리 수정없이 기본적인 환경으로 사용중입니다.

**Comment by Riey** [comment]
저도 버전은 같은데 PREEDIT_NOTHING밖에 안나오네요..

**Comment by lindoli** [comment]
카카오톡에서의 한글 입력 문제는 2.4.0 버전에서도 여전한데 해결방도는 없을까요?

![kimekaerr](https://user-images.githubusercontent.com/79091785/114293834-75800300-9ad4-11eb-9bde-2b15370926ea.png)

**Comment by Riey** [comment]
[kakao.tar.gz](https://github.com/Riey/kime/files/6291276/kakao.tar.gz)

이걸 wine regedit으로 등록해보세요

**Comment by lindoli** [comment]
감사합니다. 레지스트리 파일으로 문제가 말끔히 해결되었습니다.

**Comment by chwnam** [comment]
PlayOnLinux  같은 GUI 사용자를 위한 팁을 하나 더 남깁니다.

PlayOnLinux 실행 후  '구성'을 누릅니다.
![image](https://user-images.githubusercontent.com/6630320/114327950-1e326f00-9b76-11eb-9550-6c8f58800bd7.png)


버튼을 누르면 열리는 대화상자에서 '카카오톡'(이 부분 각자 설치하면서 이름을 다르게 주었을 것입니다)을 선택합니다.
wine 탭을 선택 하면, '레지스트리 편집기'가 보일 것입니다. 클릭해 열어줍니다.
![image](https://user-images.githubusercontent.com/6630320/114328156-a9ac0000-9b76-11eb-92ee-7c1de67b122f.png)


레지스트리 편집기가 열립니다. 여기서 레지스트리(R) > 레지스트리 가져오기 (I) 를 선택합니다.
저 위에 Riey님이 올려주신 [kakao.tar.gz](https://github.com/Riey/kime/files/6291276/kakao.tar.gz)의 파일을 선택합니다.
![image](https://user-images.githubusercontent.com/6630320/114328274-0a3b3d00-9b77-11eb-8be6-cf1c234df625.png)

그 다음 카카오톡을 실행하고, 한글 입력이 잘 되는지 확인하세요!
