### ISSUE TITLE
Arch Linux Gnome 40 Wayland Issue

### ISSUE THREAD

**Issue by Netr0y** [Riey/kime#421]
Arch Linux, Gnome 40 Wayland Installed

`[dhy0613@netroy-laptop ~]$ yay -Q | egrep 'gnome-shell|mutter'`
`gnome-shell-git 1:40.0+7+g75cba51b7-1`
`mutter-git 40.0+14+ge3bd76449-1`

AUR kime-bin installed

`[root@netroy-laptop ~]# RUST_BACKTRACE=1 kime-wayland `
`thread 'main' panicked at 'Failed to connect wayland display: XdgRuntimeDirNotSet', src/frontends/wayland/src/main.rs:394:45
stack backtrace:`
`note: Some details are omitted, run with ``RUST_BACKTRACE=full`` for a verbose backtrace.`
`[root@netroy-laptop ~]# echo $WAYLAND_DISPLAY`

`[root@netroy-laptop ~]# echo $DISPLAY`
`:0`
`[root@netroy-laptop ~]# echo $XDG_RUNTIME_DIR`

after set XDG_RUNTIME_DIR and WAYLAND_DISPLAY

[dhy0613@netroy-laptop ~]$ RUST_BACKTRACE=full kime-wayland 
thread 'main' panicked at 'Failed to connect wayland display: NoCompositorListening', src/frontends/wayland/src/main.rs:394:45
stack backtrace:
   0:     0x55cbad63fd0e - <unknown>
   1:     0x55cbad616e5c - <unknown>
   2:     0x55cbad63f411 - <unknown>
   3:     0x55cbad63ec91 - <unknown>
   4:     0x55cbad65c968 - <unknown>
   5:     0x55cbad65c8dc - <unknown>
   6:     0x55cbad65c88d - <unknown>
   7:     0x55cbad6158d0 - <unknown>
   8:     0x55cbad617502 - <unknown>
   9:     0x55cbad60ad0e - <unknown>
  10:     0x55cbad621813 - <unknown>
  11:     0x55cbad6134b9 - <unknown>
  12:     0x7fa0e7194b25 - __libc_start_main
  13:     0x55cbad60892a - <unknown>
  14:                0x0 - <unknown>

**Comment by Netr0y** [comment]
XDG_RUNTIME_DIR 및 WAYLAND_DISPLAY 변수는 각각

/run/user/1000
$XDG_RUNTIME_DIR/wayland-0로 설정했습니다.

**Comment by Riey** [comment]
현재 wayland 구현은 wlroots 기반 컴포지터만 지원합니다 이 링크를 읽어보시면 도움이 되실겁니다https://github.com/korean-input/issues/issues/6

현 상황에선 좀 어렵습니다 GNOME은 예전부터 IBUS 통합을 밀어와서...

**Comment by Netr0y** [comment]
빠른 답변 감사합니다 :)
