### ISSUE TITLE
QT 앱 실행시 undefined symbol: _ZdlPvm, version Qt_5 오류

### ISSUE THREAD

**Issue by hellojaccc** [Riey/kime#424]
KDE 5.21 / Endeavouros

qt 앱을 실행했을 때 
`symbol lookup error: /usr/lib/qt/plugins/platforminputcontexts/libkimeplatforminputcontextplugin.so: undefined symbol: _ZdlPvm, version Qt_5` 와 같은 오류가 발생합니다.

**Comment by Riey** [comment]
롤링 릴리즈 배포판은 다음 릴리즈까진 소스 패키지를 설치해 주세요

**Comment by Riey** [comment]
아치 Qt 버전이 업데이트돼서 터진줄 알았는데 그건 아니였네요 `pacman -Qs qt5-base` 버전과 nm -D `문제가 되는 프로그램` | grep qt_version해서 어느 버전을 사용중인지 확인해 보시길 바랍니다

**Comment by hellojaccc** [comment]
$ pacman -Qs qt5-base
5.15.2-5

$ nm -D /usr/bin/kate | grep qt_version
U qt_version_tag@Qt_5.15

**Comment by Riey** [comment]
kime 소스 패키지로 설치하면 작동하나요?

**Comment by hellojaccc** [comment]
> kime 소스 패키지로 설치하면 작동하나요?

네 소스 패키지로 설치하면 오류는 안 뜨네요

**Comment by nakoo** [comment]
I reopened this issue since I found this issue is still relevant with Debian Bullseye (11).

```bash
user@host:~$ hostnamectl 
  Operating System: Debian GNU/Linux 11 (bullseye)
            Kernel: Linux 5.10.0-6-amd64
      Architecture: x86-64
```

I tried to run Krita while running Kime, but the same error is shown below.

```bash
user@host:~$ krita
krita: symbol lookup error: /usr/lib/x86_64-linux-gnu/qt5/plugins/platforminputcontexts/libkimeplatforminputcontextplugin.so: undefined symbol: _ZdlPvm, version Qt_5
```

More interestingly, this issue didn't happened with keepassxc which uses the same Qt 5 library, but using v5.14.

```bash
user@host:~$ nm -D /usr/bin/keepassxc | grep qt_version
                 U qt_version_tag@Qt_5.14

user@host:~$ nm -D /usr/bin/krita | grep qt_version
                 U qt_version_tag@Qt_5.15
```

Now I'm trying to build myself to test it out whether this error still occurr with latest git commit.

**Comment by nakoo** [comment]
> Now I'm trying to build myself to test it out whether this error still occurr with latest git commit.

Tested. Can confirm this issue doesn't happen with latest git commit.
