### ISSUE TITLE
Add Wayland frontend

### ISSUE THREAD

**Issue by Riey** [Riey/kime#43]
## Blocking

- [ ] https://github.com/swaywm/sway/pull/4932
- [ ] https://github.com/swaywm/sway/pull/5890 (optional)

## Reference

* https://github.com/swaywm/wlroots/blob/master/examples/input-method-keyboard-grab.c
* https://dcz_self.gitlab.io/posts/input_method/

**Comment by simnalamburt** [comment]
[Link of input-method-unstable-v2](https://github.com/swaywm/wlroots/blob/master/protocol/input-method-unstable-v2.xml)

input-method-unstable-v2 is not accepted to [wayland-protocols] yet, but it's used by wlroots, waypipe, and others anyway.

#### References
- https://dcz_self.gitlab.io/posts/input_method/
- https://lists.freedesktop.org/archives/wayland-devel/2018-August/039255.html

**Comment by Riey** [comment]
I found input-method-unstable-v2 protocol

https://github.com/grelltrier/zwp-input-method

**Comment by simnalamburt** [comment]
I've setup development environment for this. I'll start implement this from now on.

**Comment by Riey** [comment]
@simnalamburt Are you working on? I'm going to checkout mentioned sway's pr and finish this

**Comment by simnalamburt** [comment]
I am but you are welcomed to do that. Go ahead :)

2021년 1월 25일 (월) 22:54, Riey <notifications@github.com>님이 작성:

**Comment by simnalamburt** [comment]
Note for those who are looking for the https://github.com/swaywm/sway/pull/4932 PR:

Patched version of sway has been published into AUR, as [**sway-im**](https://aur.archlinux.org/packages/sway-im/). Please take a look!

###### References
- https://aur.archlinux.org/packages/sway-im/
- https://github.com/simnalamburt/PKGBUILD/tree/main/sway-im
