### ISSUE TITLE
아래아한글에서 파일저장시 한글 미지원 

### ISSUE THREAD

**Issue by lindoli** [Riey/kime#438]
한컴 리눅스용 한글 2020 베타 버전에서 파일을 저장할 때 파일명이 한글로 입력되지 않습니다. 

한글 2020 베타 버전에선 한글 입력이 잘 되지만, 파일 저장시에만 한글 입력이 되질 않습니다.

**Comment by Riey** [comment]
뭔가 저번에 spectacle인가 걔가 안된다던것과 같은 이유가 아닌가 싶네요

**Comment by lindoli** [comment]
일부 QT 프로그램 가운데, spectacle하고 ksnap 등의 프로그램에서 편집시 입력되는 문자 위치가 뒤바끼는 현상이고, 파일 저장시에는 한글입력이 가능합니다만, 한컴 리눅스용 한글2002 베타버전은 파일 저장시에만 한글 입력이 안되는 문제입니다. 어쩌면 QT 경로와 관련이 있을지도 모릅니다. 일부 IM에서 한글 입력이 안되어 한글2020내의 QT 경로를 삭제한 적이 있는데, 이와 관련이 있는건지는 좀 더 확인해 보겠습니다.

**Comment by lindoli** [comment]
다시 한번 점검해 보았는데, 죄송하게도 제 시스템 문제였습니다. 올린 이슈의 해결책은 시스템의 /usr/lib64/qt5/plugins/platforminputcontexts 경로에 libkime-qt-버전.so 모듈이 올바르게 위치하면 되는데, 제 시스템의 경우에는 이 모듈이 없어져서 이슈되었던 것이고, 이것을 사용하지 않고 한글 자체의 im 모듈로 적용되도록 하려면 한글내의 qt5/plugins/platforminputcontexts 경로에 libkime-qt 모듈을 넣어 주는 방식을 사용하면 되더군요. 시스템 문제로 인해서 잘못된 이슈가 오히려 한글2020 버전내에서 kime으로 한글을 입력할 수 있는 다른 방법을 깨닫게 주는 기회가 된 것 같군요. 잠시나마 물의를 드려 죄송하네요.

**Comment by Riey** [comment]
한글이나 zoom같이 qt가 딸려나오는 애들은 그런식으로 하는게 이상적인거 같습니다
