### ISSUE TITLE
v2.4.0 컴파일 오류 

### ISSUE THREAD

**Issue by lindoli** [Riey/kime#451]
2.4.0 버전을 컴파일하는데 다음과 같이 enum-map 컴파일 단계에서 오류가 발생하는데, 어떻게 조치를 하면 될까요?

   Compiling enum-map v1.0.0
error[E0658]: const generics are unstable
  --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/enum-map-1.0.0/src/internal.rs:28:15
   |
28 | impl<V, const N: usize> Array<V> for [V; N] {
   |               ^
   |
   = note: see issue #74878 <https://github.com/rust-lang/rust/issues/74878> for more information

error: aborting due to previous error

For more information about this error, try `rustc --explain E0658`.
error: could not compile `enum-map`

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error: build failed

**Comment by Riey** [comment]
rust 버전이 1.51.0 이상이여야 합니다

**Comment by lindoli** [comment]
감사합니다. rust를 업그레이드한 후 정상적으로 컴파일되었습니다.
