### ISSUE TITLE
/etc/xdg/kime/config.yaml 파일이 사라졌습니다.

### ISSUE THREAD

**Issue by chwnam** [Riey/kime#460]
Kime 2.5.1 설치 후, indicator의 아이콘 색이 검정으로 바뀌는 일이 있어 다시 흰색으로 돌리려고 했습니다.

기본 yaml 파일의 구조도 바뀐 것 같아 전역 설정을 다시 복사해서 로컬인 `~/.config/kime` 디렉토리에 복사하려고 했는데,
 `/etc/xdg/kime/config.yaml` 파일이 존재하지 않습니다.

경로가 바뀐 건가요? 아니면 뭔가 문제가 있는 건가요?
경로가 변경된 거라면 문서에 언급된 전역 설정 파일의 위치를 수정해야 할 것 같습니다.

![image](https://user-images.githubusercontent.com/6630320/114482440-8d28ca00-9c41-11eb-9724-cb7d9ec78d1b.png)
(config.yaml.bak 은 제가 임시로 만든 백업 파일입니다)

**Comment by Riey** [comment]
일단 2.5.0부터 기존 설정과는 호환이 되지 않습니다 그래서 기본 설정인 검정 아이콘으로 변한것 같습니다

새 설정은 저장소의 https://github.com/Riey/kime/blob/develop/docs/CONFIGURATION.ko.md랑 `/usr/share/doc/kime/default_config.yaml`을 참고하시면 됩니다

아이콘만 바꾸신다면

```yaml
indicator:
  icon_color: White
```

이렇게 하시는걸 추천드립니다 나머지 설정은 기본 설정으로 대체됩니다

**Comment by Riey** [comment]
그리고 설정이 제대로 됐는지는 `kime-check`을 한번 써보세요.

**Comment by chwnam** [comment]
잘 알겠습니다.

문서에서는:
> /etc/xdg/kime/config.yaml에 기본값으로 설정된 파일이 있습니다. 

지금 댓글로는:
> /usr/share/doc/kime/default_config.yaml을 참고하시면 됩니다.

라고 하시는 것을 보니 오류라기 보다는 문서를 업데이트해야 할 것 같군요.

**Comment by Riey** [comment]
아 그렇군요 그쪽을 신경쓰지 못한것 같습니다
