### ISSUE TITLE
PhpStorm에서 한/영 전환이 일어나지 않는 현상이 발생힙니다.

### ISSUE THREAD

**Issue by chwnam** [Riey/kime#475]
이건 nimf 에서도 발생하던 증상인데요,

phpStorm에서 갑자기 한/영 전환이 되지 않고 오직 영문으로만 입력이됩니다. 
kime을 죽이거나 다시 띄우는 걸로는 해결이 되지 않고, 오직 phpStorm 자체를 완전히 죽인 다음 다시 띄워야 해결이되어요.
창을 모두 죽여야 해서 작업 중 흐름이 끊겨 많이 불편합니다.

이 버그는 전에 없다가, 최근 2.5버전에 오면서 자주 일어납니다.

**Comment by Riey** [comment]
아마 kime-xim이 죽은거 같은데 입력 안될때 `$XDG_RUNTIME_DIR/kime.err` 내용이 뭔가요?

**Comment by Riey** [comment]
[kime-dev.tar.gz](https://github.com/Riey/kime/files/6362894/kime-dev.tar.gz)

시험삼아서 이거 설치해보시죠

**Comment by chwnam** [comment]
오우... 설치해보니 이건 처음부터 아예 한영전환이 되지 않아요. PhpStorm이랑 WebStorm 같은 JetBrains 계열 IDE에서는 공통으로 발생하군요. 일단 IDE외에서는 정상적으로 한/영 전환은 됩니다.

**Comment by Riey** [comment]
@chwnam 올린건 냅두고 2.5.2에서 kime.err가 어떻게 나오는지 알아야 해결이 가능할것 같습니다

**Comment by chwnam** [comment]
@Riey  그럼 2.5.2 버전으로 롤백한 다음, kime.err 파일을 계속 지켜보고 있다가 에러가 나면 여기에 리포트해 드리겠습니다.

**Comment by chwnam** [comment]
@Riey 

`tail -f $XDG_RUNTIME_DIR/kime.err`로 계속 로그를 추적해 봤습니다. 한/영 전환이 되지 않는 순간에 아래  로그가 찍히기는 합니다.
 
```
[ INFO] destroy_ic
[ INFO] destroy_ic
[ INFO] XConnected with 134267538
[ INFO] IC created style: PREEDIT_NOTHING | STATUS_NOTHING, spot_location: Point { x: 0, y: 0 }
[ INFO] IC created style: PREEDIT_CALLBACKS | STATUS_CALLBACKS, spot_location: Point { x: 0, y: 0 }
```
하지만 로그가 전부 INFO 레벨만 나오네요. 이 로그는 별로 도움이 되지는 않는 것 같습니다. 에러 레벨을 높이는 방법을 잘 모르겠어요.

증상이 날 때 웹브라우저 같은 데로 커서를 돌렸다가 다시 IDE로 들어오니 정상적으로 한/영 전환이 되네요. 전에는 그렇게 되지 않았던 것 같았습니다.

저로서는 체크해 볼 것이 있습니다.
* 로그 레벨을 더 낮춰서 DEBUG 로그가 있다면? (로그 레벨을 조절하는 방법을 모르겠습니다.)
* IDE에서는 어떤 에러가 나오지 않을까?
* 구체적으로 한/영 전환이 되지 않는 조건은?

**Comment by chwnam** [comment]
며칠동안 사용하면서 한두번정도 한-영 전환이 되지 않는 증상을 겪었습니다만, 다른 창으로 이동했다가 다시 돌아오면 문제가 해결되었습니다. 물론 입력기 자체에 어떤 현상이 있었다면 수정하는 것이 더 좋겠지만, 사용하는 입장에서 우회하는 방법을 찾아내었으므로 더 이슈로 놔 두지 않아도 될 것 같습니다. 이게 입력기의 문제라고 단정지을수도 없는 상황이기도 하니까요.
