### ISSUE TITLE
소스 빌드 시에 scripts/build.sh -ar 시 에러

### ISSUE THREAD

**Issue by opensupport-ceo** [Riey/kime#482]
소스 빌드 시에 scripts/build.sh -ar 시 에러가 하기와 같이 나옵니다.

`Compiling clang-sys v1.2.0
   Compiling textwrap v0.11.0
   Compiling regex v1.4.5
   Compiling pad v0.1.6
error: failed to run custom build command for `libdbus-sys v0.2.1`

Caused by:
  process didn't exit successfully: `/home/bini/docker___/kime/target/release/build/libdbus-sys-bfac4c6089a14097/build-script-build` (exit code: 101)
  --- stdout
  cargo:rerun-if-env-changed=DBUS_1_NO_PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG
  cargo:rerun-if-env-changed=DBUS_1_STATIC
  cargo:rerun-if-env-changed=DBUS_1_DYNAMIC
  cargo:rerun-if-env-changed=PKG_CONFIG_ALL_STATIC
  cargo:rerun-if-env-changed=PKG_CONFIG_ALL_DYNAMIC
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_SYSROOT_DIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR

  --- stderr
  thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Failure { command: "\"pkg-config\" \"--libs\" \"--cflags\" \"dbus-1\" \"dbus-1 >= 1.6\"", output: Output { status: ExitStatus(ExitStatus(256)), stdout: "", stderr: "Package dbus-1 was not found in the pkg-config search path.\nPerhaps you should add the directory containing `dbus-1.pc\'\nto the PKG_CONFIG_PATH environment variable\nNo package \'dbus-1\' found\nPackage dbus-1 was not found in the pkg-config search path.\nPerhaps you should add the directory containing `dbus-1.pc\'\nto the PKG_CONFIG_PATH environment variable\nNo package \'dbus-1\' found\n" } }', /home/bini/.cargo/registry/src/github.com-1ecc6299db9ec823/libdbus-sys-0.2.1/build.rs:6:70
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
error: build failed
`

위와 같이 소스 빌드 시 에러가 납니다.

**Comment by Riey** [comment]
의존성을 전부 설치해주세요

**Comment by Riey** [comment]
찾기 귀찮으시면 도커파일에 있는대로 설치하시면 됩니다.

**Comment by opensupport-ceo** [comment]
Dockerfile 에 나와 있는 아래의 의존성을 설치하니 build.sh -ar 로 컴파일이 잘 됩니다.

참고로, Dockerfile에서 의존성 설치한 것은 아래와 같습니다.

> apt-get update
> apt-get install -y curl apt-utils
> curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --default-toolchain stable --no-modify-path --profile minimal
> rustc --version
> apt-get install -y build-essential git gcc libclang-11-dev cmake extra-cmake-modules pkg-config zstd
> apt-get install -y libpango1.0-dev libcairo2-dev libgtk2.0-dev libgtk-3-dev libglib2.0 libxcb1
> apt-get install -y qtbase5-dev qtbase5-private-dev libqt5gui5

컴파일이 잘 되었고 
이 이슈는 close하셔도 될 것 같습니다.
