### ISSUE TITLE
텔레그램에서 한글입력 전환이 안됩니다.

### ISSUE THREAD

**Issue by opensupport-ceo** [Riey/kime#483]
우분투 20.04 LTS 버전을 사용 중인데

텔레그램 데스크탑 버전을 다운로드 하여 사용하려는데

한영전환이 안되고 Kime indicator에 한영키를 눌러도 "A"라는 표시가 한글로 전환이 안됩니다.

물론 한글 입력도 전혀 안되고요, 영어 입력은 잘됩니다.

어떤 문제가 있는 건가요?

그럼 확인 부탁드립니다.

**Comment by Riey** [comment]
어떤 방식으로 설치하신건가요?

**Comment by Riey** [comment]
snap 쓰시면 kime은 못씁니다 거기서 제공하는 라이브러리들만 쓸수있어요

**Comment by Riey** [comment]
관련 문의가 많은거 같아서 FAQ에 정리해뒀습니다

**Comment by chwnam** [comment]
텔레그램을 우분투 20.04에서 사용하실 때 snap 버전 대신 네이티브 설치 버전을 사용하시면 됩니다. 패키지 이름은 'telegram-desktop'' 입니다.
