### ISSUE TITLE
kate관련 자잘한 버그

### ISSUE THREAD

**Issue by phi-friday** [Riey/kime#493]
영문에서는 이상 없음.
기존에 입력된 문자열이 있을때
ctrl-a로 전체 선택 후 한글자 입력시
기존 문자열이 남은 상태로 한글자까지 입력되고
두번째 글자로 넘어가면 ctrl-a로 잡은 기존 문자열이 사라짐.

대부분의 경우 ctrl-a로 잡고 한글자만 입력하기보다 여러 글자를 입력할테니
크게 중요한 문제는 아닐듯.
그래도 일단 발견했으니 올림.

아치, kde, xorg

**Comment by JellyBrick** [comment]
![peek](https://user-images.githubusercontent.com/16558115/119184049-d88b8f00-baaf-11eb-9640-a0db06677100.gif)

Gentoo, KDE, xorg에서 재현 가능합니다

**Comment by Riey** [comment]
kate 자체의 버그같습니다 다른 입력기로도 테스트 해보실수 있으신가요?

**Comment by phi-friday** [comment]
> kate 자체의 버그같습니다 다른 입력기로도 테스트 해보실수 있으신가요?

그러게요..
혹시나해서 tian으로 해봤는데 증상이 같네요.
