### ISSUE TITLE
도와주세요. xed (리눅스 민트 기본 GUI 텍스트 에디터) 에서 한영 변환이 전혀 되지 않아요.

### ISSUE THREAD

**Issue by chwnam** [Riey/kime#501]
이상해요. xed는 그동안 kime에서 계속 한/영 전환이 늘 잘 되던 프로그램이고,
저는 kime 업데이트를 하지 않았습니다.

그런데 얼마전부터 xed에서 계속 한/영 전환이 되지 않아요.
설정도 바꾸지 않고 그대로 쓰는데, 무슨 문제인지 모르겠습니다.

**Comment by chwnam** [comment]
그리고 제가 쓰는 PhpStorm에서도 동일하게 한/영 전환이 되지 않네요.
전에 한/영 전환 후에 입력 먹통이 되는 이슈(#475)를 말씀 드렸는데, 이젠 아예 변경조차 되지 않습니다.

**Comment by Riey** [comment]
`XDG_SESSION_TYPE`이 뭘로 돼있나요?

**Comment by chwnam** [comment]
> `XDG_SESSION_TYPE`이 뭘로 돼있나요?

`x11` 으로 되어 있군요.

**Comment by chwnam** [comment]
@Riey 
PhpStorm 2021.1.3 업데이트 이후 한글 입력은 정상적으로 동작합니다.

**Comment by Riey** [comment]
터미널에서 `G_MESSAGES_DEBUG=kime`으로 설정하시고 로그가 어떻게 나오는지 알려주세요

**Comment by chwnam** [comment]
xed 를 터미널에서 실행하고 나오는 로그를 말씀하시는 건가요?
한영키 입력시 별다른 로그가 나오지 않습니다. 혹시 다른 로그를 원하시면 경로를 말씀해 주세요.

**Comment by Riey** [comment]
환경변수를 저렇게 설정해도 아무런 로그가 안나오나요?

**Comment by chwnam** [comment]
@Riey  네. 다른 키 입력에 대해서는 어떤 로그들이 나왔지만 한/영 키에 대해서는 로그가 나오지 않더군요.

**Comment by Riey** [comment]
음 한영키를 Shift + Space 같은걸로 한번 바꿔보실래요?

**Comment by chwnam** [comment]
@Riey 죄송합니다만, configuration 문서만 보고서는 한영키를 Shift+Space 로 바꾸는 방법을 알기가 어렵습니다. 알려주셨으면 해요...

한편 config.yaml 파일에서 로그를 TRACE 레벨로 낮추고 xed 를 실행하고 한영키를 입력해 봤는데 다음처럼 로그가 찍히더군요. 

```
[DEBUG] (1) kime_indicator: Update: Hangul
[DEBUG] (1) kime_indicator: Update: Latin
```

다른 데에서 한영키를 입력하면, 한글일 때는 `[DEBUG] (1) kime_indicator: Update: Hangul` 하나만 나옵니다. 다시 한글에서 영어로 입력할 때는 `[DEBUG] (1) kime_indicator: Update: Latin`하나만 로그가 찍힙니다.

그런데 xed 에서만 한영키 1번에 저 두 줄이 동시에 찍히는 현상이 일어나네요.

**Comment by chwnam** [comment]
@Riey 
버그가 종잡을 수 없어 조금 당황스럽습니다. 

xed 에서 한글이 입력 안 되는 문제를 해결할 수 있었습니다. 일전에 #475 에서 PhpStorm 한영 전환 문제 때문에 config.yaml 설정을 수정한 적이 있습니다. 그 때 했던 설정은 아래 내용과 같습니다.

```
indicator:
  icon_color: White
log:
  global_level: INFO
engine:
  global_hotkeys:
    AltR:
      behavior:
        Toggle:
          - Hangul
          - Latin
      result: Bypass
```
여기서 `engine:` 이하 부분을 삭제했더니 xed에서 다시 정상적으로 한영 전환이 가능해졌습니다. 다행입니다. :)

그런데요, 이제는 다른 심각한(?) 버그가 발생합니다.
PhpStorm, PyCharm, WebStorm 등에서 한/영 전환이 되지 않는 현상이 발생합니다.
혹시나 싶어 `engine:` 부분을 삭제한 것이 문제인가 싶어 복구해 봤는데, 그래도 증상이 없어지지 않습니다.
한/영 전환 문제가 왠지 여기에서 저기로 옮겨간 것 같군요...

**Comment by chwnam** [comment]
리눅스 민트 20.2를 새로 설치하고 PhpStorm 및 Xed 에서 kime 2.5.3 버전으로 위에서 언급한 어떤 버그 없이 잘 동작하는 것을 확인했습니다. 이슈를 종료하겠습니다.
