### ISSUE TITLE
config.yaml 단축키 수정이 안 됩니다

### ISSUE THREAD

**Issue by woncheol-kim** [Riey/kime#510]
한영 전환 단축키를 shift-space로 바꾸고, layout을 sebeolsik-3-90으로 바꿨는데요,
수정을 해도 디폴트로만 실행돼서 삽질 끝에 단축키 수정이 문제였다는 결론을 내렸습니다.
단축키를 건드리지 않고 layout만 바꾸는 건 되는데, 단축키를 건드리면 layout 설정까지 무력화됩니다.

아치리눅스(EndevourOS) + Xfce 커널 5.13.12 / kime 2.5.5-1입니다.

**Comment by Riey** [comment]
단축키를 바꾼 설정을 올려주실수 있으신가요?

**Comment by woncheol-kim** [comment]
Super-Space:
      behavior:
        Toggle:
          - Hangul
          - Latin
      result: Consume

여기서 Super-Space를 여러 가지로 바꿔 봤습니다:
Shift-Space
ShiftL-Space
Control-Space
ControlL-Space

어떤 경우건 예외 없이 layout 설정까지 무력화되던데요.

**Comment by Riey** [comment]
S-Space나 C-Space로 하시면 될겁니다 설정이 제대로 불러와지는지는 kime-check를 실행해보시면 됩니다

**Comment by woncheol-kim** [comment]
감사합니다. S-Space와 C-Space 둘 다 넣어 봤는데 어쩐 일인지 S-Space는 안 먹네요. 그래도 C-Space가 잘 되니까 대충 만족합니다.
