### ISSUE TITLE
[Feature Request] Add support for Dubeolsik reordering like nimf

### ISSUE THREAD

**Issue by 7k5x** [Riey/kime#512]
![Screenshot_20210828_223507](https://user-images.githubusercontent.com/88917536/131222298-2054b1a4-3009-45bc-bdbe-970a2ba6f5f1.png)
The highlighted menu in `nimf` is called `debeolsik reordering`, and it auto-reorders debeolsik characters to prevent typos. For example, `ㅏㄹ` automatically becomes `라`. I find this a very neat feature of `nimf`. I would like to see this feature in `kime`.

한국어 번역: 님프에 `두벌식 재배열`(정확한 한국어 이름은 모름)이라는 기능이 있습니다. 이 기능은 한국어 모음하고 자음을 자동으로 재배열하는 건데(예를 들면 `ㅏㄹ`이 `라`로 재배열`) 오타 방지에 꽤나 좋은 님프만의 기능이라고 생각합니다. 이 기능을 구현해주시면 님프에서 kime으로 갈아타겠습니다.

**Comment by Jhyub** [comment]
https://github.com/Riey/kime/blob/develop/docs/CONFIGURATION.md#flexiblecomposeorder 이거 사용하시면 될 듯 합니다

**Comment by 7k5x** [comment]
아 이미 있었네요
좀 더 읽어보고 이슈 올릴걸 했네요
