### ISSUE TITLE
Enabling typing of choseong twin letters within sebeolsik layout while not replacing a single letter with a twin one in the present character when starting to type the next character when FlexibleComposeOrder is applied

### ISSUE THREAD

**Issue by wind0204** [Riey/kime#520]
sebeolsik-3-91 레이아웃에서 ComposeChoseongSsang 사용하면 '사서' 라고 입력하면 ' 싸ㅓ' 가 입력되고, 사용안하면 '써야' 라고 입력하면 'ㅅ서야' 라고 입력이 되는 문제가 있습니다.

설정파일을 손보는 방법으로 해결할 수 있는 문제일까요?

**Comment by wind0204** [comment]
FlexibleComposeOrder 를 사용하지 않아야 ComposeChoseongSsang 사용하여 쌍자음초성 사용이 가능해지네요. 그렇게 설정하면 세벌식의 별미인 모아치기가 안 되는 단점이 있어서 아쉽습니다!

**Comment by wind0204** [comment]
사 입력되었을때 초성 ㅅ 이 입력되는 경우 사에서 ㅅ가 이미 쌍자음이 아닌 초성으로 결정이 난 것으로 판단해서 쌍자음으로 변화하지 않게 결정하는 로직이 구현되어 있으면 좋겠네요!

**Comment by Riey** [comment]
중성이 있을경우 조합이 안되도록 해야겠네요 구현은 쉬운데 어떤식으로 도입할지 좀 고민해봐야겠습니다

**Comment by Riey** [comment]
`사 + ㅅ` = 싸 이걸 원하고 `ㅅㅏㅅ`를 입력하진 않을테니 다른 애드온을 두기보다 그냥 버그라고 보고 현재 ComposeChoseongSsang 동작을 수정할려고 하는데 어떠신가요

**Comment by wind0204** [comment]
`사 + 초성ㅅ = 사ㅅ` 로 봉인해버리는 방법과,
`사 + 초성ㅅ = 싸` 허용하지만 두번째 중성이나 종성이 입력되면 싸를 사로 고치고 다음 글자에 초성ㅅ을 생성하는 방법이 있겠네요. 제가 윈도우즈에서 사용하던 날개셋 한글입력기에서 어떻게 반응했는지 한번 확인해봐야겠습니다...

**Comment by wind0204** [comment]
제가 사용하던 날개셋 한글입력기는 `사 + 초성ㅅ = 사ㅅ` 로 봉인해버리는군요. `사 + ㅅ = 싸`가 되지 않네요.
말씀하신대로 ComposeChoseongSsang 를 수정하셔도 좋을 것 같습니다!

**Comment by Riey** [comment]
네 아무래도 그게 직관적이고 좋아보여요
