### ISSUE TITLE
ComposeChoseongSsang과 FlexibleComposeOrder 동시 사용 문제

### ISSUE THREAD

**Issue by kiwiyou** [Riey/kime#526]
ComposeChoseongSsang과 FlexibleComposeOrder이 모두 켜진 상태에서 ㄱ + ㅏ + ㄱ 이 가ㄱ가 아닌 까로 입력됩니다. 때문에 '가가'와 같은 단어를 입력할 수 없는 문제가 발생합니다.

**Comment by Riey** [comment]
Seems duplicate of #520

**Comment by Riey** [comment]
Please wait until new release come or use develop version
