### ISSUE TITLE
210928 아치리눅스 gnome 사용자인데 kime 이 동작을 안합니다..

### ISSUE THREAD

**Issue by sephid86** [Riey/kime#527]
이렇게 훌륭한 입력기를 만들어주신것에 감사한 마음을 가지고

데비안 그놈 환경에서 kime 입력기를 잘 사용하다가 아치리눅스로 넘어왔습니다.

그놈 4.0.4 에 wayland 입니다.

AUR 에서 yay -S kime 으로 설치했는데

작동을 안합니다.. 제가 뭔가 놓치고 있는것이 있을까요

.xinitrc, .xprofile, .xsession

export GTK_IM_MODULE=kime                                                       
export QT_IM_MODULE=kime       
export XMODIFIERS=@im=kime

이거 해봐도 동작을 안합니다.

ps ax 보면 분명히 kime 보이긴 합니다.

근데 동작을 안해요.. ㅠㅠ

제가 놓치고 있는것이 무엇일까요..

**Comment by OctopusET** [comment]
wayland gnome에서는 ibus 외의 다국어 입력기 사용이 불가능합니다.
다음 이슈 참고 부탁드립니다.
https://github.com/Riey/kime/issues/421

**Comment by Riey** [comment]
정확히는 거기서도 wayland-im말고는 다 입력됩니다 alacritty나 그놈 검색창같은 것들은 안되고 파폭같은건 됩니다

**Comment by sephid86** [comment]
빠른 답변 감사드립니다.

그럼 gnome 에서 kime 을 이용하려면 xorg 를 이용하면 될까요?

**Comment by sephid86** [comment]
kime 에서 wayland 지원 계획은 없으신가요?

**Comment by Riey** [comment]
그냥 하고싶다고 되는게 아니라서요 자세한건 https://github.com/Riey/kime/issues/527#issuecomment-928411739에 링크 보시길 바랍니다
