### ISSUE TITLE
파이어폭스에서 Ctrl, Alt, Shift 등의 modifier나 방향키를 누르면 입력 칸을 지워버리는 문제가 있습니다.

### ISSUE THREAD

**Issue by pbzweihander** [Riey/kime#528]
아치 리눅스, 최신 커널, 최신 stable 파이어폭스를 사용하고 있습니다.

파이어폭스의 주소창이나 구글 스프레드시트, 노션 등에서 컨트롤, 알트, 시프트, 방향키를 누르면 현재 선택되어있는 입력 칸이 전부 지워지는 문제가 있습니다.

kime랑 어떤 관련이 있는지는 짐작도 가지 않지만 kime를 종료하면 발생하지 않습니다.

**Comment by pbzweihander** [comment]
아 Wayland와 sway를 사용 중입니다!

**Comment by Riey** [comment]
저도 똑같이 사용하는데 재현이 되진 않네요

**Comment by Riey** [comment]
한글이나 영어 상관없이 모든 입력이 지워지나요?

**Comment by pbzweihander** [comment]
네. 한글 영어 모두 지워지고 현재 모드가 한글이나 영어 상관없이 지워집니다.

모든 입력가능한 UI나 html 요소에 대해 지워지는 것도 아니고, 주소창이나, 일부 입력 요소만 지워집니다.

ctrl 등을 누르면 항상 지워지는 것도 아니고, 대체로 처음 포커스가 간 이후 첫 키 입력이 상기한 키 일때 지워집니다.

**Comment by Riey** [comment]
> kime랑 어떤 관련이 있는지는 짐작도 가지 않지만 kime를 종료하면 발생하지 않습니다.

종료란건 어떤걸 종료하신건가요?

**Comment by pbzweihander** [comment]
다음과 같은 systemd service 파일을 사용중입니다:

```
[Unit]
Description=Korean IME
PartOf=graphical-session.target

[Service]
Type=simple
ExecStart=/usr/bin/kime -D --log info

[Install]
WantedBy=sway-session.target
```

`systemd --user start kime` 으로 실행하고, `systemd --user stop kime` 으로 종료했습니다.

**Comment by Riey** [comment]
그건 좀 이상한게 kime 데몬이 없어도 파이어폭스 동작에는 전혀 영향이 없어야 하거든요 종료해도 한글입력은 문제없이 되시죠?

**Comment by pbzweihander** [comment]
아니요 kime 프로세스(와 kime-wayland 등의 프로세스)가 종료되면 파이어폭스에서도 한글 입력이 되지 않습니다

**Comment by Riey** [comment]
wayland-im으로 입력되나 보네요 GTK_IM_MODULE이 kime으로 설정됐는지 확인해보세요

**Comment by pbzweihander** [comment]
GTK_IM_MODULE 환경 변수를 주니까 해결되었습니다. 새 머신을 세팅했는데 이걸 깜빡했군요. 감사합니다!

**Comment by seobi** [comment]
> 아치 리눅스, 최신 커널, 최신 stable 파이어폭스를 사용하고 있습니다.
> 
> 파이어폭스의 주소창이나 구글 스프레드시트, 노션 등에서 컨트롤, 알트, 시프트, 방향키를 누르면 현재 선택되어있는 입력 칸이 전부 지워지는 문제가 있습니다.
> 
> kime랑 어떤 관련이 있는지는 짐작도 가지 않지만 kime를 종료하면 발생하지 않습니다.

저도 같은 현상이 발생합니다.
파이어폭스에서 구글 스프레드시트 사용할 때, 데이터가 있는 여러 셀을 복사하려고 Ctrl+C 를 누르면 첫번째 셀이 지워집니다.
저도 archlinux + sway 환경입니다.
