### ISSUE TITLE
Gnome + wayland 사용이 가능하네요..?

### ISSUE THREAD

**Issue by sephid86** [Riey/kime#559]
작년에 Gnome 40 wayland 에서 동작 안한다는 답변을 들었는데

방금 테스트 해보니 작동을 합니다.. ;;

아치리눅스 Gnome 42 입니다.

**Comment by Riey** [comment]
GTK나 QT는 문제 없고요 wayland 어플들만 문제가 됩니다

**Comment by sephid86** [comment]
Gnome 40 wayland 에서는 kime 이 동작 자체를 안했었는데...

그때 주신 답변도 xorg 에서 사용가능하다 하셨었어요..

말씀하신 wayland 어플은 예를 들자면 어떤것을 말씀하시는건가요?

wayland 에서 안되면 GTK 나 QT 라이브러리 에서도 안되는게 맞는거 아닌지요

**Comment by Riey** [comment]
> 말씀하신 wayland 어플은 예를 들자면 어떤것을 말씀하시는건가요?

alacritty나 intellij등은 wayland 프로토콜로 통신하는데 이게 gnome에선 ibus밖에 못써요

GTK나 QT는 자체 플러그인 api를 사용하기 때문에 상관없고요

**Comment by sephid86** [comment]
아.. 그래서 kime 동작하지 않는 프로그램에선 저절로 ibus 가 작동한거였구나...

답변 감사합니다.
