### ISSUE TITLE
cachyos 에선 인디케이터 autostart가 되지 않습니다

### ISSUE THREAD

**Issue by k24w24** [Riey/kime#576]
cachyos(아치리눅스 베이스) 사용자 입니다.
매번 konsole에서 kime를 불러야만 인디케이터가 뜹니다.

- kde 환경
- yay로 설치 
- kime.desktop 에 X-DBUS-StartupType에 wait나 unique를 넣어도 소용 없네요.
- 인디케이터가 안 보여도 한영전환등엔 문제가 없고, 
- 컨픽파일도 적용이 된 상태입니다.
 
다 좋은데 매번 매뉴얼로 인디케이터를 기동해야 하는 게 불편하네요.

** **
걍 autostart에 kime-indicator를 직접 등록시켰습니다. 
이미 kime는 실행된 상태고, 더 필요한 건 인디케이터 뿐이니 나쁘지 않네요.

**Comment by Jhyub** [comment]
유사한 이슈를 겪고 있습니다. Arch + KDE 사용중이며 기존에는 작동했으나 어느 시점부터 작동하지 않는 것으로 보입니다.

**Comment by dontdieych** [comment]
저도 아치 쓰는데 같은 증상입니다.

인디케이터가 트레이에 보이지는 않는데 한글 입력은 됩니다. `pgrep kime -l` 해보면 아무것도 없습니다. 이 때 터미널에서 kime을 실행하면 인디케이터가 보이면서 프로세스가 보입니다.

```
a@archlinux ~> pgrep kime -l
a@archlinux ~ [1]> #한글 입력은 가능
a@archlinux ~ [1]> kime
a@archlinux ~> pgrep kime -l
102795 kime
102797 kime-xim
102799 kime-indicator
a@archlinux ~> # 트레이에 인디케이터가 보입니다. 역시 한글 입력에 이상 없음
```

~/.config/environment.d/envvars.conf
```
MOZ_ENABLE_WAYLAND=1
GTK_IM_MODULE=kime
QT_IM_MODULE=kime
XMODIFIERS=@im=kime
PLASMA_USE_QT_SCALING=1
```

```
a@archlinux ~> env|grep kime
GTK_IM_MODULE=kime
XMODIFIERS=@im=kime
QT_IM_MODULE=kime
a@archlinux ~>
```

```
Operating System: Arch Linux
KDE Plasma Version: 5.25.5
KDE Frameworks Version: 5.98.0
Qt Version: 5.15.6
Kernel Version: 5.19.9-arch1-1 (64-bit)
Graphics Platform: X11
```
