### ISSUE TITLE
JetBrains IDE 사용시 한/영 전환이 안되는 경우

### ISSUE THREAD

**Issue by Shane-Park** [Riey/kime#582]
혹시 비슷한 상황 겪는 분들 있으신가요?

IntelliJ IDEA 에서 평상시에는 한/영 전환이 잘 되는데
꼭, `Ctrl + Shift + F` 로 전체 찾기 하거나 `Shift + Shift` 에서 검색 할 때 영문만 쳐지더라고요

제 개인적인 해결 방법은 그 상태에서 IntelliJ IDEA 외의 다른 화면 (웹 브라우저 등) 을 클릭 하고 한/영 키를 두어번 정도 눌러서 한/영 전환을 해 주다가 다시 인텔리제이로 돌아오면 한영 전환이 당분간은 잘 되더라고요.
이 방법으로 라도 해결이 되기는 하는데 혹시 원인이나 더 좋은 해결책을 아는 분 있으면 공유 부탁드려요

**Comment by chwnam** [comment]
네! 아주 최근은 별로 이 현상을 겪은 적이 드뭅니다만, 종종 겪었습니다.
저는 PhpStorm을 자주 쓰는데요, 그러하면 버그가 JetBrains IDE 계열에서 자주 나는 것 같습니다. 

제 경우는 이랬습니다. 해당 버그는 한글만 쭉 사용했을 때도 나타나긴 하나, 주로 한 - 영을 오가면서 작업할 때 두드러지게 나타났었습니다.예를 들어 Markdown 문서 작성라든지 HTML 코딩이라든지요. 

예전에 이 일로 Riey 님과도 직접 디스코드 챗을 했던 것으로 기억합니다만, 정확하게는 모르겠네요.
저도 이 문제를 해결하기 위해서는 다른 창을 활성화시켰다가 다시 돌아오는, 동일한 방법을 사용했습니다. 

저는 현재 Linux Mint 21을 사용하고 있습니다. 그리고 여기에 v2.5.6 Ubuntu 21.10 용 deb 파일을 설치해 쓰고 있어요.
최근 PhpStorm 에서는 이 버그는 별로 만나지 못해 살짝 잊고 있었는데, 아직 IntelliJ 에서는 버그가 많이 발생하나 보군요.

**Comment by Shane-Park** [comment]
IntelliJ IDEA 2022.3 으로 업데이트 된 후 해당 문제가 해결되었습니다.
패치노트에는 자세히 봐도 관련 내용이 없었는데 어떤식으로 해결된지는 잘 모르겠습니다.

- intellij idea 2022.3
- KIME v3.0.1 
 
위와 같이 사용중이며 입력기 문제 전혀 없을 정도로 매끄럽습니다. 혹시 관련 이슈 있는분들은 둘 다 업데이트 해보세요! 이슈 close 하겠습니다

**Comment by isac322** [comment]
- intellij idea 2022.3
- KIME v3.0.1
- OS: manjaro
- Desktop: KDE X11

이 환경인데 한영전환이 안됩니다ㅠ log 옵션을 debug로 바꾸고 `kime -D` 실행한 다음 IntelliJ에서 한영 전환을 마구 해보면 아래같은 로그가 나옵니다. 바로 이어서 kwrite을 열어서 한영전환해보면 잘 동작합니다.

```
[ INFO] Initialized
thread 'main' panicked at 'Failed to connect wayland display: NoCompositorListening', src/frontends/wayland/src/main.rs:400:45
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[ INFO] Found previous XIM_SERVER it will overrided
[ INFO] Start server win: 102760448
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/frontends/xim/src/handler.rs:45:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[ INFO] Process kime-xim has exit with exit status: 101
[ INFO] Process kime-wayland has exit with exit status: 101
[DEBUG] (1) kime_indicator: Update: Hangul
[DEBUG] (1) kime_indicator: Update: Hangul
[DEBUG] (1) kime_indicator: Update: Latin
[DEBUG] (1) kime_indicator: Update: Hangul
```

**Comment by honnip** [comment]
설정에 `xim_preedit_font`의 폰트가 설치되어 있는지 확인해 보세요.
