### ISSUE TITLE
Kime-check 실행시 panic 발생

### ISSUE THREAD

**Issue by eldeshue** [Riey/kime#585]
WSL2, Ubuntu 20.04 사용중에 있습니다. intellij 관련 오류로 인해서 kime 배포판 받아서 쓰는 중입니다.
설치 및 각종 설정 완료하고 intellij 실행했음에도 한글 설정이 되질 않아서 kime-check 돌려보는데 다음과 같이 panic이 발생하여 문의드립니다. git을 비롯하여 리눅스 사용 자체가 미숙하여 여기에 문의드리오니 부디 너그러이 여겨주시면 감사하겠습니다.

// ------------------------ 이하 오류 메시지 -------------------------- //
 kime-check                                                                                                                                            
KIME_API_VERSION: 6
Ok       Engine api version
Found icon: /usr/share/icons/hicolor/64x64/apps/kime-hangul-black.png
Found icon: /usr/share/icons/hicolor/64x64/apps/kime-hangul-white.png
Found icon: /usr/share/icons/hicolor/64x64/apps/kime-latin-black.png
Found icon: /usr/share/icons/hicolor/64x64/apps/kime-latin-white.png
Ok       Check icons exists
Loading config path: /etc/xdg/kime/config.yaml
Ok       Config file
Ok       Engine works
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: NotPresent', src/tools/check/src/main.rs:140:68
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
// -------------------------------------------------------------------- //

이상입니다. 읽어주셔서 감사합니다.

**Comment by Riey** [comment]
환경변수가 제대로 설정 안된거 같은데 WSL는 지원하지 않습니다. 직접 설정하셔야 하는데 리눅스 사용이 익숙하지 않으시다면 어려울 것 같습니다.

**Comment by eldeshue** [comment]
친절한 답변 감사합니다. 역시 리눅스의 세계는 넓고도 깊군요... 부디 건승하시고 좋은 일 가득하시기 바랍니다!
