### ISSUE TITLE
wayland 세션에서 qt와 gtk를 사용하지 않는 프로그램들 한글 입력 불가

### ISSUE THREAD

**Issue by nemorami** [Riey/kime#604]
wayland 세션에서 emacs, intellij 등 qt와 gtk를 사용하지 않는 프로그램들은 한글을 입력할수가 없습니다.
kime-check를 실행하면
Ok       Config file                   
Ok       Engine works                  
Ignore   XMODIFIERS has @im=kime       (Session type is wayland not x11)
Ok       GTK_IM_MODULE has kime        
Ok       QT_IM_MODULE has kime         
Ok       LANG has UTF-8    
이렇게 나옵니다.

다른 입력기에서는 wayland세션에서도  XMODIFIERS=@im=<입력기> 이렇게 설정해서 
입력이 가능합니다.

**Comment by Riey** [comment]
배포판을 뭘 쓰시나요? kime-xim이랑 kime-wayland가 켜져있는지 확인해보세요

**Comment by nemorami** [comment]
배포판을 archlinux입니다.

처음에 실행되어 있는 프로세스는 kime 과 kime-indicator 입니다. 

kime-xim을 실행시킨 후에는 정상적으로 입력됩니다.

그런데 kime-wayland는 실행시킬때 에러가 나네요..

**Comment by icarusnine** [comment]
저도 동일한 증상이 발생하네요.
Ubuntu 20.04에서 발생하고 kime-wayland 실행시에 다음과 같은 로그가 나옵니다.

thread 'main' panicked at 'Load InputManager: Missing', src/frontends/wayland/src/main.rs:404:10
stack backtrace:
   0: rust_begin_unwind
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:515:5
   1: core::panicking::panic_fmt
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/panicking.rs:92:14
   2: core::result::unwrap_failed
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/result.rs:1599:5
   3: kime_wayland::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
[8493:8522:1130/110453.710024:ERROR:connection_handler_impl.cc(402)] Received message of invalid type 84
[8493:8522:1130/110453.710050:ERROR:connection_factory_impl.cc(472)] ConnectionHandler failed with net error: -4

**Comment by Riey** [comment]
> 저도 동일한 증상이 발생하네요.
> Ubuntu 20.04에서 발생하고 kime-wayland 실행시에 다음과 같은 로그가 나옵니다.
> 
> thread 'main' panicked at 'Load InputManager: Missing', src/frontends/wayland/src/main.rs:404:10
> stack backtrace:
>    0: rust_begin_unwind
>              at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:515:5
>    1: core::panicking::panic_fmt
>              at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/panicking.rs:92:14
>    2: core::result::unwrap_failed
>              at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/result.rs:1599:5
>    3: kime_wayland::main
> note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
> [8493:8522:1130/110453.710024:ERROR:connection_handler_impl.cc(402)] Received message of invalid type 84
> [8493:8522:1130/110453.710050:ERROR:connection_factory_impl.cc(472)] ConnectionHandler failed with net error: -4
> 
> kime 실행 후에도 intellij 에서 한글 입력이 동작하지 않습니다.

우분투같은 gnome은 wayland 입력을 ibus를 내장해서 하기 때문에 kime을 사용할수 없습니다.

**Comment by Cruising0904** [comment]
저도 arch 사용중인데 kime-wayland 입력시 
![image](https://user-images.githubusercontent.com/29267295/230834482-3f628303-bfeb-41f1-ac0d-eddf2aa9fbd3.png)
ㅇ이렇게만 나오고 있습니다. 현재 사용중인 터미널은 kitty 입니다

**Comment by Jhyub** [comment]
동일한 증상이 발생합니다. kime-wayland가 다음 에러를 출력하며 종료되며, kime-wayland 단일 실행, kime 실행 모두 해당합니다.
```
thread 'main' panicked at 'Load InputManager: Missing', src/frontends/wayland/src/main.rs:410:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: queue 0x55d5383f29e0 destroyed while proxies still attached:
  wl_seat@3 still attached
  wl_registry@2 still attached
```

환경은 다음과 같습니다.
 * Distro: Arch Linux
 * wayland 1.22.0-1
 * plasma-desktop 5.27.5-1
 * kime-git 3.0.2.r3.ged8f31e-1 (AUR의 kime, kime-bin 모두 시도해보았으나 동일합니다)

[fcitx5의 경우](https://www.csslayer.info/wordpress/linux/use-plasma-5-24-to-type-in-alacritty-or-any-other-text-input-v3-client-with-fcitx-5-on-wayland/)를 참고하여 Virtual Keyboard로 kime를 설정해보았으나 작동하지 않았습니다.
plasma-wayland-protocols를 설치해보았고 설치한 후 kime를 다시 빌드해보았으나 작동하지 않았습니다.

@nemorami 혹시 사용중이신 de가 plasma라면 plasma와의 궁합 문제인 것으로 좁힐 수 있을 것 같습니다.
