### ISSUE TITLE
[Chromium + wayland + gtk4] You have to press enter twice to commit word

### ISSUE THREAD

**Issue by OctopusET** [Riey/kime#613]
When you run chromium with gtk4 on Wayland (not Xwayland),
```
chromium  --enable-features=UseOzonePlatform,WebRTCPipeWireCapturer --ozone-platform=wayland  --gtk-version=4
```
You have to press enter twice to commit word. I tested on Google Docs and search bar.

This might be chromium issue, because gtk4 text-input support is not perfect. If Wayland native input protocol support is merged, it could be solved.

Version info:

> chromium : 108.0.5359.124-1
> kime: 3.0.1-1
> brave: 1.46.153-1
> ArchLinux: Latest Update (2023-01-10)

**Comment by OctopusET** [comment]
This might be duplicated issue.
https://github.com/Riey/kime/issues/606

**Comment by Riey** [comment]
> This might be duplicated issue.
> https://github.com/Riey/kime/issues/606

I mark this as duplicated. Feel free to reopen when #606 solution doesn't resolve this issue.
