### ISSUE TITLE
release에 `libkime-qt5-5.12.10.so` 추가

### ISSUE THREAD

**Issue by scarf005** [Riey/kime#615]
#272 의 방법을 사용하려고 하는데, 현재 [우분투 5.13.4 (711)](https://zoom.us/download?os=linux) 버전에서는 qt 5.12.10 버전을 사용중인 것 같습니다.
![image](https://user-images.githubusercontent.com/54838975/212320380-45104eea-0858-46c4-93b0-ff00b0517162.png)

`libkime-qt5-5.12.10.so` 버전도 준비해주실수 있을까요?

**Comment by Riey** [comment]
5.12.9같이 패치버전만 다른 라이브러리를 사용하셔도 똑같이 작동할겁니다

[](https://wiki.qt.io/Qt-Version-Compatibility)

> Patch releases are both backwards and forwards binary and source compatible.

**Comment by scarf005** [comment]
붙여넣은 이후로 zoom을 실행하자마자 꺼져버리고 apt purge 후에 재설치해도 그대로네요
이건 나중에 좀 더 알아봐야할것 같습니다

**Comment by scarf005** [comment]
![hangul input on zoom](https://user-images.githubusercontent.com/54838975/212526549-b2942c0f-2695-47cf-ac79-779fbd33666e.png)
껐다 키니 잘 동작하네요 확인해주셔서 감사합니다!

![inputmethod settings](https://user-images.githubusercontent.com/54838975/212526565-9f301b82-5641-4db5-84f1-6ddea4ac46db.png)

![/opt/zoom/platforminputcontexts](https://user-images.githubusercontent.com/54838975/212527027-c7bff580-3c3f-4d9f-a027-ec4ea486eeda.png)
