### ISSUE TITLE
kime가 시작시 실행이 안됩니다.

### ISSUE THREAD

**Issue by ktkalpha** [Riey/kime#639]
EndeavourOS(아치 기반) KDE 쓰고 있습니다
/etc/xdg/autostart에는 kime.desktop 이 있는데 실행이 안됩니다.
실행이 안되있어도 한글입력이 되기는 한데
kime-xim이 실행이 안되서 마인크래프트 등에서 입력할때 번거롭습니다.
![image](https://github.com/Riey/kime/assets/57173745/939a967e-62a4-498b-b1e2-77be9fc2dba0)

**Comment by Jhyub** [comment]
#629 에서 해결된 이슈입니다. 다음 릴리즈에서 고쳐질 예정입니다.

**Comment by Riey** [comment]
`kime-git` 패키지를 설치하면 문제가 해결되나요?

**Comment by ktkalpha** [comment]
네 kime, kime-xim, kime-indicator 다 실행이 됩니다
