### ISSUE TITLE
sway 에서 kime 을 이용하는 가장 올바른 설정방법 입니다.

### ISSUE THREAD

**Issue by sephid86** [Riey/kime#647]
안녕하세요.

sway 에서 kime 을 아주 감사한 마음으로 사용중인 유저입니다.

최근에 다른 DE 들은 입력기 설정을 직접 관리하는 매니저 프로그램을 내장하여

손쉽게 입력기를 바꿀수 있고 DE 간 세션이동에도 문제가 잘 발생하지 않도록
예전에 비해 많이 발전한것 같습니다.

sway 에서는 kime 이용시 environment 설정을 제대로 해주지 않으면 
끝글자 버그가 나타나는등 정상적인 동작을 보이지 않습니다.

일례로 GTK_IM_MODULE=kime 을 export 하여 kime 을 작동시키는 경우

터미널에서 libreoffice --calc 를 직접 입력하여 실행하면 끝글자 버그가 나타나지 않지만
sway 런쳐를 이용해서 libreoffice 를 실행하면 끝글자 버그가 나타납니다.

**아래와 같은 방법을 이용하면 sway 런쳐를 이용해도 kime 이 정상적으로 동작합니다.**

제 경험상 kime 은 sway 에서 가장 신뢰할수 있고 안정적으로 동작하는 한글 입력기 입니다.

(자음 특수문자가 안되는것은 슬프지만..)

sway 에서 kime 을 이용하는 아래의 방법을 정리하여 kime github readme 에 올려주신다면

올바르게 동작하는 kime 으로 sway 유저들의 불편함이 줄어들 것이고

잘못된 설정으로 인한 오동작으로 kime 에 대한 오해가 생기는 일을 줄일수 있을것이라고 생각합니다.

제글이 작은 도음이라도 되었으면 하는 바램이며
더 좋은 방법이 있다면 가르침을 주시길 조심스럽게 청합니다.

p.s 아래 글자 크기가 왜 거대해지는지 .. 
github 게시판 에디터 사용에 미숙해서 죄송합니다.

-
아래는 다른 커뮤니티에서 제가 작성한 원문 글과 링크입니다.
https://www.clien.net/service/board/cm_linux/18367454
https://www.clien.net/service/board/cm_linux/18072522
-

gnome 이나 kde 또는 xfce

다른 DE 들과 sway 를 설치해서 세션을 옮겨가며 사용하게되면
한가지 문제가 발생하게 됩니다.

sway 에서 설정해야 하는 환경 변수가 다른 DE 들과 달라서
어느 한쪽 에서는 정상적인 동작이 되지 않는 경우가 생기는 문제 입니다.

화면공유를 이용할 경우 gnome 과 sway 가
서로 사용하는 컴포지터의 라이브러리가 달라서 설정해야 하는 환경변수가 다르고

DE 마다 서로 다른 한글입력기를 이용할 경우도 설정해야 하는 환경변수가 다릅니다..

따라서

/etc/environment 또는 ~/.bashrc 에서 환경변수를 export 해버리면

어느 한쪽 에서는 정상적인 동작이 되지 않는 경우가 생깁니다.

이 문제를 저는 아래와 같이
sway 에서 사용하는 환경변수를 분리하는 방법으로 해결하였습니다.
-
$ sudo vi /usr/share/wayland-sessions/sway.desktop 파일을 수정합니다.

Exec=sway 이 부분을 아래처럼 수정해줍니다.
Exec=env XDG_CURRENT_DESKTOP=sway GTK_IM_MODULE=kime QT_IM_MODULE=kime XMODIFIERS=@im=kime sway

$ sudo vi ~/.config/sway/config - sway 설정파일에 아래 내용 추가 (또는 /etc/sway/config

input * xkb_options korean:ralt_hangul,korean:rctrl_hanja
exec kime

그리고 저처럼 로그인 데몬을 이용하지 않고
터미널에서 sway 를 직접 타이핑 하여 사용하시는 분들은 아래 작업을 한번 더 해주시면 됩니다.
-
$ vi ~/.bashrc 에서 아래 내용 추가해줍니다.
alias sway='env XDG_CURRENT_DESKTOP=sway GTK_IM_MODULE=kime QT_IM_MODULE=kime XMODIFIERS=@im=kime sway'

**Comment by Riey** [comment]
좋은글 감사합니다 그래도 여기는 이슈 트래커이니 해당 내용은 Discussion에 올리시는게 맞는것 같습니다

**Comment by sephid86** [comment]
> 좋은글 감사합니다 그래도 여기는 이슈 트래커이니 해당 내용은 Discussion에 올리시는게 맞는것 같습니다

discussion 이 뭔가요?

제가 깃허브는 저장소로만 써서 이용 방법을 잘 모릅니다 ㅎㅎ

gnome 에게 ibus 가 있다면 

kime 은 sway 이용자에게 유일한 희망입니다..

hyprland 도 요즘 급부상 하던데 sway 처럼 wlroots 를 이용해서 
kime 이 가장 잘 맞았습니다.

kime 이 ibus 가 접근하지 않는 모든 영역을 장악하게 되기를 바랍니다.

**Comment by Riey** [comment]
> > 좋은글 감사합니다 그래도 여기는 이슈 트래커이니 해당 내용은 Discussion에 올리시는게 맞는것 같습니다
> 
> discussion 이 뭔가요?
> 
> 제가 깃허브는 저장소로만 써서 이용 방법을 잘 모릅니다 ㅎㅎ
> 
> gnome 에게 ibus 가 있다면 
> 
> kime 은 sway 이용자에게 유일한 희망입니다..
> 
> hyprland 도 요즘 급부상 하던데 sway 처럼 wlroots 를 이용해서 
> kime 이 가장 잘 맞았습니다.
> 
> kime 이 ibus 가 접근하지 않는 모든 영역을 장악하게 되기를 바랍니다.
> 

https://github.com/Riey/kime/discussions

이쪽을 다른 사이트 게시판처럼 이용하시면 됩니다
