### ISSUE TITLE
Caps lock을 활용하여 한영전환 하는 방법이 있을까요?

### ISSUE THREAD

**Issue by dayo05** [Riey/kime#652]
안녕하세요! 현재 Asahi linux + wayland(Hyprland)기반의 WM을 활용하고 있습니다.
Caps lock을 활용하여 한영전환을 하는 방법을 지원하는지와, 만일 그렇다면 어떤 방식으로 config file을 수정해야 되는지를 알고 싶습니다!

감사합니다 :)

**Comment by damhiya** [comment]
KMonad 같은 프로그램으로 capslock에 다른 키를 매핑하고, kime에서 그 키로 한영전환을 하도록 설정할 수 있습니다

**Comment by dayo05** [comment]
> KMonad 같은 프로그램으로 capslock에 다른 키를 매핑하고, kime에서 그 키로 한영전환을 하도록 설정할 수 있습니다

과거 xkb evdev설정 다이렉트로 건드려서 remap한적은 있으나, 이경우 업데이트시마다 pacman이 관련 설정을 게속 건드는듯한... 문제가 발생해서 가능하면 자체 기능으로 해결하고자 합니다.

일단 WM쪽에서 건드려보는 경우에도 뭔가가 이상하게 안되는거같기에 일단 조금 더 알아봐야될꺼같기도 하고요.

일단 kime에서 내부적으로 지원하지 않는다는걸로 받아드려도 될까요?

**Comment by Riey** [comment]
네 현재로선 지원하지 않습니다.
