### ISSUE TITLE
막강한 kime 도 새로나온 Cosmic DE 에서는 속수무책 인 거 같네요.

### ISSUE THREAD

**Issue by gitnewbie8** [Riey/kime#689]
Cosmic App 들이  cosmic-file-manager, cosmic-terminal, cosmic-editor 등등인데, 애네들은 kime 뿐만 아니라 ibus ,fcitx5 도 전혀 맥을 못춥니다.

kime 은 그래도 될 줄 알았는데 kime 도 안되네요?

**Comment by Riey** [comment]
해당 이슈는 cosmic의 지원여부에 달린거라 여기에 다실게 아닙니다
